Fix stability of SUnitTest's related to the  process monitoring
guillep/pharo-core pull request #10514
Opened 2021-11-27 13:06 UTC by dionisiydk

It contributes to #10429

2021-11-29 09:19 UTC, guillep requested changes

2021-11-29 09:19 UTC, guillep commented on src/SUnit-Tests/SUnitTest.class.st
> +	case forkedProcesses: forkedProcesses.
Would be nice to not repeat the code between this, `testHangedChildProcessTestWhenLeftProcessIsConsideredAsFailure`,`testHangedTestDueToFailedChildProcess`, `testFailedTestWithFailedChildProcessTestShouldNotEffectFollowingAno` and `testFailedChildProcessTest`

2021-11-29 12:01 UTC, MarcusDenker commented
- [CI] Failing randomly: StPlaygroundPageTest>>testContents #10519

2021-11-30 11:18 UTC, MarcusDenker commented
```
New failing - 5
windows-64 / Tests-windows-64 / testFailedChildProcessTestShouldNotEffectFollowingAnotherTest – Windows64.SUnit.Tests.Core.SUnitTest
<1s
windows-64 / Tests-windows-64 / testFailedTestWithFailedChildProcessTestShouldNotEffectFollowingAnotherTest – Windows64.SUnit.Tests.Core.SUnitTest
<1s
windows-64 / Tests-windows-64 / testSmokeTestForDemoPages – Windows64.Spec2.Tests.Examples.SpDemoTest
<1s
windows-64 / Tests-windows-64 / testFailedChildProcessTestShouldNotEffectFollowingAnotherTest – Windows64.SUnit.Tests.Core.SUnitTest
<1s
windows-64 / Tests-windows-64 / testFailedTestWithFailedChildProcessTestShouldNotEffectFollowingAnotherTest – Windows64.SUnit.Tests.Core.SUnitTest
<1s
Existing failures - 9
unix-64 / Tests-unix-64 / testFailedChildProcessTestShouldNotEffectFollowingAnotherTest – Unix64.SUnit.Tests.Core.SUnitTest
<1s
unix-64 / Tests-unix-64 / testFailedTestWithFailedChildProcessTestShouldNotEffectFollowingAnotherTest – Unix64.SUnit.Tests.Core.SUnitTest
<1s
unix-64 / Tests-unix-64 / testFailedChildProcessTestShouldNotEffectFollowingAnotherTest – Unix64.SUnit.Tests.Core.SUnitTest
<1s
unix-64 / Tests-unix-64 / testFailedTestWithFailedChildProcessTestShouldNotEffectFollowingAnotherTest – Unix64.SUnit.Tests.Core.SUnitTest
<1s
osx-64 / Tests-osx-64 / testDynamicVariable – MacOSX64.Kernel.Tests.Processes.ProcessSpecificTest
10s
osx-64 / Tests-osx-64 / testFailedChildProcessTestShouldNotEffectFollowingAnotherTest – MacOSX64.SUnit.Tests.Core.SUnitTest
<1s
osx-64 / Tests-osx-64 / testFailedTestWithFailedChildProcessTestShouldNotEffectFollowingAnotherTest – MacOSX64.SUnit.Tests.Core.SUnitTest
<1s
osx-64 / Tests-osx-64 / testFailedChildProcessTestShouldNotEffectFollowingAnotherTest – MacOSX64.SUnit.Tests.Core.SUnitTest
<1s
osx-64 / Tests-osx-64 / testFailedTestWithFailedChildProcessTestShouldNotEffectFollowingAnotherTest – MacOSX64.SUnit.Tests.Core.SUnitTest
```

2021-12-07 14:30 UTC, merged

2021-12-07 14:30 UTC, guillep commented
Thanks!