10214 improving comments and adding tests to tree searcher
guillep/pharo-core pull request #10636
Opened 2021-12-10 10:19 UTC by AlessHo

Adding more tests + Enhancing class RBParseTreeSearcher

2021-12-10 10:28 UTC, Ducasse commented
Thanks a lot Aless for your contribution. We will have a look. 
Having more tests is super nice. Thanks again.

2021-12-10 20:59 UTC, gcotelli requested changes
- Use proper names instead of `dict`
- Method comments are formatted in an strange way
- The cases when the searcher is not matching can be changed to do `self fail` in the do block instead of checking for nil (I'm proposing one of that changes in this review)
- There's a lot of almost repeated assertions, like
```
self
		assert:
		(dict at: (RBPatternVariableNode named: '`@arg')) formattedCode
		equals: 'offset + count'.
```
extract it to something receiving the context (dict) and the variable name, something like:
`assertCodeForVariableNodeNamed: name in: context equals: expectedCode`

2021-12-10 20:59 UTC, gcotelli commented on src/AST-Core-Tests/RBParseTreeSearcherTest.class.st
> +	"self halt."
Remove this debugging code, even if it's commented.

2021-12-10 20:59 UTC, gcotelli commented on src/AST-Core-Tests/RBParseTreeSearcherTest.class.st
> +	"
```suggestion
	"Here we are looking for multiple lists in one match pattern at the same time. 
	Lists can be any receiver or arguments"
```

2021-12-10 20:59 UTC, gcotelli commented on src/AST-Core-Tests/RBParseTreeSearcherTest.class.st
> +	"self deny: dict isNotNil"
```suggestion
	"Here we are looking for multiple lists in one match pattern at the same time. 
	Lists can be any receiver or argument"

	searcher
		matches: '`@receiver assert: `@arg equals: true'
		do: [ :aNode :answer | self fail ].

	searcher executeTree:
		(self parseExpression: 'self assert: token isLiteralToken.').
```

2022-01-03 10:27 UTC, MarcusDenker commented
This PR just needs a pass over the comments of the reviewer

2022-01-19 21:56 UTC, Ducasse commented
Aless can you have a look?

2022-01-24 08:08 UTC, MarcusDenker commented
@AlessHo

2022-01-24 08:12 UTC, AlessHo commented
Hello, Okay

2022-01-24 08:14 UTC, AlessHo commented
Hello,

I just saw the messages.
Ok, noted for the comments I will adjust them this week.
Thank you for your reviews.

2022-01-28 11:09 UTC, merged