Add support for traits in RBAddClassRefactoring
guillep/pharo-core pull request #10977
Opened 2022-03-09 10:17 UTC by sonibla

Hello there

I added
RBAddClassRefactoring >> addClass:superclass:subclasses: **traits:** category:
to support traits in refactorings

Please correct me if I did it wrong

Old methods are still available (RBAddClassRefactoring >> addClass:superclass:subclasses:category:)

2022-03-09 12:20 UTC, MarcusDenker commented
tests are failing, for mac:

```
osx-64 / Tests-osx-64 / testAddClass(#rbClass->RBAddClassRefactoring) – MacOSX64.Refactoring2.Transformations.Tests.Parametrized.RBAddClassParametrizedTest
1s
osx-64 / Tests-osx-64 / testModelAddClass(#rbClass->RBAddClassRefactoring) – MacOSX64.Refactoring2.Transformations.Tests.Parametrized.RBAddClassParametrizedTest
1s
osx-64 / Tests-osx-64 / testModelChildrenToSibling(#rbClass->RBChildrenToSiblingsRefactoring) – MacOSX64.Refactoring2.Transformations.Tests.Parametrized.RBChildrenToSiblingsParametrizedTest
2s
osx-64 / Tests-osx-64 / testCopyPackage(#rbClass->RBCopyPackageRefactoring) – MacOSX64.Refactoring2.Transformations.Tests.Parametrized.RBCopyPackageParametrizedTest
1s
osx-64 / Tests-osx-64 / testCopyPackageAndChangesCopyReferences(#rbClass->RBCopyPackageRefactoring) – MacOSX64.Refactoring2.Transformations.Tests.Parametrized.RBCopyPackageParametrizedTest
1s
osx-64 / Tests-osx-64 / testSplitClass(#rbClass->RBSplitClassRefactoring) – MacOSX64.Refactoring2.Transformations.Tests.Parametrized.RBSplitClassParametrizedTest
```

2022-03-09 16:36 UTC, sonibla commented
I forgot the case where there are no traits being used, my bad

2022-03-15 15:21 UTC, demarey requested changes
Thank you for the PR.
It will be too short for Pharo10, better to target Pharo 11.
This PR is missing tests for traits support.
Also, not related to this PR, but Refactorings should be rewritten to do not use text but a model instead (like Ring).

2022-03-15 15:21 UTC, demarey commented on src/Refactoring-Core/RBAddClassRefactoring.class.st
> +	self className: aName.
there is code duplication here.
You should call `self addClass: aName superclass: aClass subclasses: aCollection category: aSymbol` and then only initialize traits i.v.

2022-03-15 15:21 UTC, demarey commented on src/Refactoring-Core/RBAddClassRefactoring.class.st
> +										  separatedBy: [ stream nextPutAll: ' + ' ] ] ])
probably this code handles only simple case, use a full traits but do not handle traits composition.

2022-03-17 16:28 UTC, sonibla commented
Thanks for your feedback @demarey 
I improved my PR a little bit but I don't feel it's enough, ideally RBClass and RBTrait would support trait compositions so that it's possible to test traits in RBAddClassParametrizedTest...

2022-03-17 18:20 UTC, closed without merging