Extend DiffMorph to make it navigable accross differences
guillep/pharo-core pull request #11641
Opened 2022-09-03 13:52 UTC by sonibla

Hello there

This PR makes it possible to add buttons to easily navigate in the text comparator

![navigableDiffPresenter](https://user-images.githubusercontent.com/49032546/188273353-8bb8570a-c834-4776-be40-7c28a3725369.PNG)

2022-09-03 14:02 UTC, sonibla commented
Adaptation of @rolandbernard 's work, credits to him

2022-09-13 06:42 UTC, demarey requested changes

2022-09-13 06:42 UTC, demarey commented on src/Tool-Diff/DiffMorph.class.st
> +	di := 1.
would it be possible to use meaningful names for `si`and `di`?

2022-09-13 06:42 UTC, demarey commented on src/Tool-Diff/DiffMorph.class.st
> +					sj := si.
would it be possible to use meaningful names for `sj` and `dj`?

2022-09-13 06:42 UTC, demarey commented on src/Tool-Diff/DiffMorph.class.st
> +						c first key = #match
would it be possible to use meaningful name for `c`?

2022-09-13 06:42 UTC, demarey commented on src/Tool-Diff/DiffMorph.class.st
> +								c do: [ :s |
would it be possible to use meaningful names for `s`?

2022-09-13 06:42 UTC, demarey commented on src/Tool-Diff/DiffMorph.class.st
> +								c do: [ :s |
would it be possible to use meaningful names for `sk` and `dk`?

2022-09-14 19:02 UTC, Ducasse commented
Ping

2022-09-17 11:54 UTC, sonibla commented
@demarey thanks for your review!
I refactored calculateAllDifferences, it's now easier to read

2022-12-03 13:29 UTC, merged