change inspect to return receiver / add inspector
guillep/pharo-core pull request #11804
Opened 2022-10-18 18:52 UTC by SabineMa

https://github.com/pharo-project/pharo/issues/11803

2022-10-18 19:18 UTC, jordanmontt approved these changes

2022-10-19 06:16 UTC, Ducasse commented
Would be good to add a test to cover that we do not get this regression.

2022-10-19 06:58 UTC, SabineMa commented
I can add

testInspector
self assert: 1 inspector class equals: SpWindowPresenter

and

testInspect
self assert: 1 inspect equals: 1


Is this ok?
I am not sure to which class.
what is the condition that the regression will not occur?

Am Mi., 19. Okt. 2022 um 08:16 Uhr schrieb StéphaneDucasse <
***@***.***>:

> Would be good to add a test to cover that we do not get this regression.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/pharo-project/pharo/pull/11804#issuecomment-1283485855>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ADJAHWFAS7QGJ4T3AFNKGZLWD6G3ZANCNFSM6AAAAAARIMC7QI>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-10-19 07:08 UTC, astares requested changes

2022-10-19 07:08 UTC, astares commented on src/Tool-Base/Object.extension.st
> +	^ Smalltalk tools inspector inspect: self.
Please no unnecessary dots at the end.

2022-10-19 08:19 UTC, jordanmontt commented
Also maybe you could add a comment in the methods as a form of documentation. For example, in the `inspect`method saying that if you can the window object you should use `inspector`

2022-10-19 08:19 UTC, Ducasse commented
Hi sabina 
Yes this sounds good to me and they should be packaged with the same tools-tests or something like that.

2022-10-19 11:35 UTC, SabineMa commented
https://github.com/pharo-project/pharo/issues/11803#issuecomment-1283836624
Please do not integrate

2022-10-19 11:35 UTC, SabineMa commented
Everything is ok as it is. I was confused.

2022-10-20 07:36 UTC, jordanmontt reviewed
As discussed in the issue, I also think we should add:

- deprecate basicInspectand renamed it to basicInspector. We still return the spec window.
- refactor inspectOnce to always return self.

2022-10-20 07:39 UTC, SabineMa commented
I already wrote the code but I have auth problems for doing the pull request. 
I have to manage other stuff with you product and will come back here asap.

2022-10-27 15:02 UTC, jordanmontt commented
Hello @SabineMa , did you have the time to commit your changes?
If not, tomorrow there is a Pharo sprint, this can be an issue for that :)

2022-11-13 10:56 UTC, SabineMa commented
closed because done here: https://github.com/pharo-project/pharo/pull/11886

2022-11-13 10:56 UTC, closed without merging