[IGNORE]21701-Add-primitive-to-change-the-window-icon
guillep/pharo-core pull request #1198
Opened 2018-04-13 23:00 UTC by VincentBlondeau

add primitive for changing the icon of the main window + TESTS
use basename instead of name on file references

2018-04-13 23:04 UTC, VincentBlondeau commented
https://pharo.fogbugz.com/f/cases/21701/Add-primitive-to-change-the-window-icon

2018-04-16 17:52 UTC, VincentBlondeau commented
The latest VM now integrates the primitive. But I do not know if it used in the CI.

2018-04-17 09:23 UTC, jecisc commented
There is now a conflict

src/Files/File.class.st

2018-04-24 02:10 UTC, VincentBlondeau commented
@jecisc No conflict anymore

2018-05-25 16:54 UTC, VincentBlondeau commented
I do not understand why the tests are failing ... they seem to be unrelated

2018-06-12 09:01 UTC, jecisc requested changes

2018-06-12 09:01 UTC, jecisc commented on src/Graphics-Tests/DisplayScreenTest.class.st
> +	^ #[0 0 1 0 6 0 0 0 0 0 1 0 32 0 199 91 0 0 102 0 0 0 128 128 0 0 1 0 32 0 40 8 1 0 45 92 0 0 64 64 0 0 1 0 32 0 40 66 0 0 85 100 1 0 48 48 0 0 1 0 32 0 168 37 0 0 125 166 1 0 32 32 0 0 1 0 32 0 168
@VincentBlondeau You need to call "super setUp" here to get the tests to pass.

2018-06-12 09:01 UTC, jecisc commented on src/Graphics-Tests/DisplayScreenTest.class.st
> +	^ #[0 0 1 0 6 0 0 0 0 0 1 0 32 0 199 91 0 0 102 0 0 0 128 128 0 0 1 0 32 0 40 8 1 0 45 92 0 0 64 64 0 0 1 0 32 0 40 66 0 0 85 100 1 0 48 48 0 0 1 0 32 0 168 37 0 0 125 166 1 0 32 32 0 0 1 0 32 0 168
For tests maybe we can find a smaller icon?

2018-06-12 09:45 UTC, philippeback commented
Any chance this can be working?

2018-06-12 09:49 UTC, jecisc commented
@philippeback Once the vm will include the primitive I think it should work. Else I think Vincent would not have done the PR yet.

2018-06-13 16:55 UTC, VincentBlondeau commented
@philippeback The primitive is integrated in the latest VM, you should be able to use it

2018-06-21 09:51 UTC, MarcusDenker commented
ok to merge?

2018-06-21 22:23 UTC, jecisc commented
@MarcusDenker I tested the generated image and it works with the current stable VM.

2018-06-21 22:26 UTC, jecisc approved these changes

2018-06-22 06:32 UTC, merged