Old class template should be in OldPharoClassPrinter
guillep/pharo-core pull request #12372
Opened 2023-01-17 19:22 UTC by hernanmd

Fix for "Old class template is still around and should be in the correct printer OldPharoClassPrinter and not Class". Issue 12171

2023-01-26 08:05 UTC, MarcusDenker commented
"This branch has conflicts that must be resolved"

2023-01-27 08:33 UTC, guillep requested changes
These methods do not have any users. Are we sure these shouldnt' be removed instead?

2023-02-24 13:07 UTC, guillep commented
@hernanmd could you solve the merge conflicts?

2023-04-29 11:18 UTC, Ducasse commented
@hernanmd Hi hernan can you have a look so that we can close this issue?

2023-06-25 17:31 UTC, Ducasse commented
I will close this PR since no progress.

2023-06-25 17:31 UTC, closed without merging