Do not resolve absolute paths to open a file
guillep/pharo-core pull request #12591
Opened 2023-02-08 11:51 UTC by jecisc

Currently to open a file we always resolve the path relatively to the… working directory

This commit changes that to resolve only in case the path is not absolute. In case of absolute path we can just use the path as it is. This could help use resolve https://github.com/pharo-project/pharo-launcher/issues/590

2023-02-08 16:26 UTC, MarcusDenker commented
failing test not related

2023-02-09 12:19 UTC, MarcusDenker approved these changes

2023-02-09 22:29 UTC, dionisiydk commented on src/FileSystem-Core/FileSystem.class.st
> +	^ store handleClass open: (FileReference fileSystem: self path: path) writable: aBoolean
It would be nice to have a test covering this logic.
Is it a bug fix or just an optimization? If former then the test is really needed.

2023-02-10 09:11 UTC, tesonep requested changes
I agree that we need a test. 
I don't like the isAbsolute question, we can delegate to the absolute path to do nothing.
There is already the extension point, we can implement the AbsolutePath >> #asResolvedBy: as just returning self.
Also, we can remove the awful if in Path >> #resolvePath:

2023-02-10 11:14 UTC, jecisc commented
I tried to do that but then my image bugs in some places because here we resolve a path with a path, but I think that in other places we do it with other resolvable and we don’t expect a path as result.

2023-03-20 02:20 UTC, closed without merging