Improve faulty parsing of byte array literal (alternative version)
guillep/pharo-core pull request #12818
Opened 2023-02-20 20:26 UTC by privat

Parsing keeps the content of faulty elements in byte array literals by interpreting the faulty element as classic literal array elements (instead of just skipping them), and put them in an instance of `RBLiteralByteArrayErrorNode` instead of in a faulty `RBLiteralByteArrayNode` instance as previously.
The old way was fragile and broke clients (including compilation and execution), since a `value` of a `RBLiteralByteArrayNode` can only contain bytes.

Note: This is an alternative implementation of #12817 — there can be only one[.](https://www.youtube.com/watch?v=sqcLjcSloXs) that is somewhat simpler (you can compare the diffs) and more robust.
The only drawback is that `RBEnglobingErrorNode` (the superclass of the error node used) need love:
* weird spaces in formatting.
* `contents` should have a `s` (I think)
* mandatory error is problematic when the error is in the content (so no specific error message on the whole compound)
But I consider these to be out of the scope of the PR and should be solved independently.

2023-02-20 20:37 UTC, privat commented
Maybe a discussion point (that also applies to #12817 ): the choice currently (and previously) done in case of error is to consume elements until a closing bracket `]`. An alternative policy could be to consider having an unfinished literal (someone forgot the `]`, or is still writing and did not enter it yet) then continue the parsing as if a `]` was present (the node is still an error node, obviously).

2023-02-21 15:24 UTC, MarcusDenker commented
I restarted the CI run and now this looks odd: It shows an error and I can not restart it anymore. Very very odd

2023-02-23 09:16 UTC, guillep approved these changes
Looks good!

I wonder, why a lot of tests are removed, is that because they seem superfluous or it is a mistake?

2023-02-23 09:45 UTC, MarcusDenker commented
I think I did the conflict resolution wrong, the tests should have been added, not removed

2023-02-23 12:34 UTC, privat commented
I rebased the commits to solve the merge

2023-02-23 13:26 UTC, guillep requested changes
The ci fails because of the syntax error I think

2023-02-23 13:26 UTC, guillep commented on src/AST-Core-Tests/RBErrorNodeParserTest.class.st
> +RBErrorNodeParserTest >> testFaultyLiterabByteArray [
There is a syntax error here...

2023-02-23 13:26 UTC, guillep commented on src/AST-Core-Tests/RBErrorNodeParserTest.class.st
> +RBErrorNodeParserTest >> testFaultyLiterabByteArray [
There is a missing closing bracket between lines 365 and 366?

2023-02-23 13:54 UTC, privat commented
oops. I shouldn't have solved the conflicts by hand in a text editor before the first coffee.

2023-02-23 15:25 UTC, privat commented
tests are ok (but the windows box is dead)

2023-02-23 16:10 UTC, MarcusDenker approved these changes

2023-02-23 16:13 UTC, MarcusDenker commented
I like this solution better than the alternative, as here we know that we have a wrong ByteArray

2023-02-24 10:08 UTC, guillep approved these changes

2023-02-24 10:09 UTC, merged