Refactor TextConstants to separate font and non-font constants (Issue : #13015)
guillep/pharo-core pull request #13249
Opened 2023-04-02 15:45 UTC by shreeshjha

This pull request addresses issue #13015 by refactoring the TextConstants class to separate font and constants. Currently, TextConstants contains both constant and fonts which can cause confusion in the code. By separating them, the code becomes more organized and easier to maintain.

2023-04-03 06:28 UTC, MarcusDenker commented
Full image load fails with:

```
MetacelloNotification: Loading -> Text-Core-tonel.1 --- tonel:///builds/workspace/est_and_branch_Pipeline_PR-13249/64/src --- cache
STONReaderError: At character 1105: 'invalid input'
```

2023-04-03 08:14 UTC, Ducasse commented
May be this is due to a bootstrap problem (did not check).

2023-04-05 15:20 UTC, jecisc requested changes
A little piece of advice: Do not comment code. Remove it. 

If we have a problem here in the future, we can use a git blame to find the old implementation. 
Keeping commented code will just make us lose time reading it and wonder "why is this here? Should I keep it working if we remove the comments?"

And most of the time, you lose way more time asking yourself those questions than just using a git blame if one day there is a problem here.

2023-04-05 15:29 UTC, shreeshjha commented
> A little piece of advice: Do not comment code. Remove it.
> 
> If we have a problem here in the future, we can use a git blame to find the old implementation. Keeping commented code will just make us lose time reading it and wonder "why is this here? Should I keep it working if we remove the comments?"
> 
> And most of the time, you lose way more time asking yourself those questions than just using a git blame if one day there is a problem here.

Thanks @jecisc I completely agree with you that keeping commented code can cause confusion and waste time. I will make sure to remove it in the next update once I figure out how to eliminate the issue that it consisted, and I appreciate your advice to use git blame (I wasn't aware of this feature, and it's good to know that it can be useful in finding the old implementation) to find the old implementation if necessary.

2023-04-05 15:38 UTC, MarcusDenker commented
so the problem is caused directly by the commenting out: the syntax of Tonnel (the one stored on git) does not allow commenting out like that.

```

 "{ #category : #accessing }
 TextConstants class >> TextSharedInformation [
 	^TextSharedInformation
 ]"

 { #category : #'backward compatibility' }
 "TextConstants class >> at: aSymbol [
 	^ self classPool at: aSymbol ifAbsent: [self TextSharedInformation at: aSymbol]
 ]"
```

2023-04-05 15:50 UTC, shreeshjha commented
> so the problem is caused directly by the commenting out: the syntax of Tonnel (the one stored on git) does not allow commenting out like that.
> 
> ```
> 
>  "{ #category : #accessing }
>  TextConstants class >> TextSharedInformation [
>  	^TextSharedInformation
>  ]"
> 
>  { #category : #'backward compatibility' }
>  "TextConstants class >> at: aSymbol [
>  	^ self classPool at: aSymbol ifAbsent: [self TextSharedInformation at: aSymbol]
>  ]"
> ```

Thanks @MarcusDenker bringing the problem to my attention. I understand that the problem was caused by the commenting out, and that the syntax of Tonnel does not allow commenting out like that (will work on this error on next commit and Thanks again for the observation).

2023-04-24 12:53 UTC, guillep commented
Hi @shreeshjha ! Thanks for the PR. Please, do not just edit the code in github, that can lead to a lot of problems :)

I'll close this PR until this is fixed, then we can reopen it or open a new PR.

2023-04-24 12:53 UTC, closed without merging

2023-04-24 13:42 UTC, shreeshjha commented
Hello @guillep Thanks for taking the time to review my PR. I'll look into this issue soon and I'll make sure to follow the correct process in the future :)