Add a MiniWorld for the externalWindow
guillep/pharo-core pull request #13639
Opened 2023-05-04 08:03 UTC by RemiDufloer

Addition of a Mini World object to represent the world of native windows.

This world is much smaller and more concentrated than WorldMorph (even if it shares part of its code, which creates duplication).

Moreover MiniWorld has less responsibility than WorldMorph.

In a future pull request the goal is to replace WorldMorph with this minimal World

2023-05-04 09:24 UTC, RemiDufloer commented
i see they have many test fail I try to fix them with a new commit today

2023-05-04 12:15 UTC, guillep commented
> i see they have many test fail I try to fix them with a new commit today

Thanks Remi

2023-05-08 16:29 UTC, Ducasse commented
Strange we get

```
Running tests of Calypso-SystemPlugins-FileOut-Queries
Running tests of NewTools-Debugger-Breakpoints-Tools
DeprecationPerformedNotification: Automatic deprecation code rewrite: The method RBMethodNode>>#method called from StHaltBreakpointInspectionItemTest>>#testNewBreakpointItem has been deprecated. use compiledMethod
DeprecationPerformedNotification: Automatic deprecation code rewrite: The method RBMethodNode>>#method called from StHaltBreakpointInspectionItemTest>>#testNewHaltItem has been deprecated. use compiledMethod
DeprecationPerformedNotification: Automatic deprecation code rewrite: The method RBMethodNode>>#method called from Breakpoint>>#printTargetForBreakpointInspection has been deprecated. use compiledMethod
DeprecationPerformedNotification: Automatic deprecation code rewrite: The method RBMethodNode>>#method called from StHaltInspectionItem>>#printEntity has been deprecated. use compiledMethod
DeprecationPerformedNotification: Automatic deprecation code rewrite: The method RBMethodNode>>#method called from StHaltBreakpointInspectionItemTest>>#testPrintHaltItem has been deprecated. use compiledMethod
[ERROR] 2023-05-04 17:15:54.000 growOldSpaceByAtLeast (Replacement/generated/64/vm/src/gcc3x-cointerp.c:47413):Required space is bigger than the headroom. Could not allocate
Context>>cannotReturn:
Context>>cannotReturn:
Delay>>unschedule
[self unschedule] in Delay>>wait in Block: [self unschedule]
```

2023-05-08 16:32 UTC, Ducasse commented
I wonder if the crash is related to one of these
`StHaltBreakpointInspectionItemTest>>#testNewBreakpointItem has been deprecated`

2023-05-12 12:36 UTC, RemiDufloer commented
> I wonder if the crash is related to one of these
> `StHaltBreakpointInspectionItemTest>>#testNewBreakpointItem has been deprecated`

I corrected the error, it was because I was doing tests that opened native windows, but the CI is running headless, so it made errors

2023-05-12 13:21 UTC, guillep requested changes
There are some problems in here!

2023-05-12 13:21 UTC, guillep commented on src/Morphic-Base/MorphicWindowManager.class.st
> +
There is a missing closing bracket here. Did you touch it directly in the repo? don't do that!

2023-05-12 13:21 UTC, guillep commented on src/Morphic-Base/MorphicWindowManager.class.st
> +
And format this method please :)

2023-05-12 13:21 UTC, guillep commented on src/OSWindow-Core/OSWindowAttributes.class.st
> +
format!

2023-05-12 13:21 UTC, guillep commented on src/OSWindow-Core/OSWindowAttributes.class.st
> +
format

2023-05-12 13:21 UTC, guillep commented on src/OSWindow-Core/OSWindowAttributes.class.st
> +
format

2023-05-12 13:25 UTC, astares commented on src/Morphic-Base/MorphicWindowManager.class.st
> +	self updateTasksBar
typically call it "updateTaskBar" (singular)

2023-05-12 13:26 UTC, astares commented on src/Morphic-Base/MorphicWindowManager.class.st
> +MorphicWindowManager >> updateTasksBar [
typically #updateTaskBar (singular)

2023-05-16 09:08 UTC, RemiDufloer commented on src/Morphic-Base/MorphicWindowManager.class.st
> +
I had a conflict when I wanted to do the pr on github, he told me that my branch was not up to date with pharo12, I told him that I wanted to keep my changes, I don't really know what who it is pass then but it seems that it broke everything :( I will try to fix that this morning

2023-05-16 09:09 UTC, RemiDufloer commented on src/Morphic-Base/MorphicWindowManager.class.st
> +MorphicWindowManager >> updateTasksBar [
oops i will fix that

2025-02-25 10:43 UTC, jecisc commented
Pharo meeting: We'll close it for now because it is outdated, but Guille will check if we can port those changes to P13

2025-02-25 10:43 UTC, closed without merging