little cleaning and optimization
guillep/pharo-core pull request #13833
Opened 2023-05-26 15:04 UTC by Enzo-Demeulenaere

little cleaning of Color

2023-05-26 15:07 UTC, guillep commented on src/Colors/Color.class.st
> -	(parm isKindOf: Color)
All this smells like we need a double dispatch

2023-05-29 11:59 UTC, jecisc requested changes

2023-05-29 11:59 UTC, jecisc commented on src/Colors/Color.class.st
> +					put: (self class
```suggestion
					put: (self
```

We already are class side so this should be #self

2023-05-29 11:59 UTC, jecisc commented on src/Colors/Color.class.st
> +	(parm isKindOf: self class)
```suggestion
	(parm isKindOf: self)
```

We are class side so this should be self

2023-05-30 22:44 UTC, jecisc commented
Tests failures are not related

2023-05-30 22:45 UTC, jecisc approved these changes

2023-05-31 05:22 UTC, merged