Replaced the random generator from Pharo.
guillep/pharo-core pull request #14230
Opened 2023-07-06 13:39 UTC by BastouP411

The current random generator of Pharo is heavily skewed in certain situations (for example the first value generated from a new seed is constrained in a certain range).

So this replaces the current generator with a new one based on Permuted Congruential Generators (https://www.pcg-random.org/index.html)

This uses a primitive implemented in pharo-project/pharo-vm#645

2023-07-06 13:43 UTC, guillep requested changes
Thanks @BastouP411, I left some comments

2023-07-06 13:43 UTC, guillep commented on src/Random-Tests/RandomTest.class.st
> +	results add: (Random primitiveRandomNumber: state) ].
Could we not have tests on private implementation-specific methods?

2023-07-06 13:43 UTC, guillep commented on src/Random-Tests/RandomTest.class.st
> +	results add: (Random primitiveRandomNumber: state) ].
same here

2023-07-06 13:43 UTC, guillep commented on src/Random-Tests/RandomTest.class.st
> +	results add: (Random primitiveRandomNumber: state) ].
and here

2023-07-06 13:43 UTC, guillep commented on src/Random-Tests/RandomTest.class.st
> +	results add: (Random primitiveRandomNumber: state) ].
and

2023-07-06 13:43 UTC, guillep commented on src/Random-Tests/RandomTest.class.st
> +	results add: (Random primitiveRandomNumber: state) ].
here.

Even all these tests look similar excepting for some values, maybe some common code could be extracted into common methods?

2023-07-06 13:43 UTC, guillep commented on src/Random-Tests/RandomTest.class.st
> +	self assert: (gen state at: 1) equals: 16r977afd8015414a94
Why testing the state and not the next number only?

2023-07-09 19:25 UTC, Ducasse commented
Can we have a nice class comment?
With a link to the exact implementation.

2023-07-09 19:36 UTC, Ducasse commented
In the class comment I would like also to have the following code 

```
// *Really* minimal PCG32 code / (c) 2014 M.E. O'Neill / pcg-random.org
// Licensed under Apache License 2.0 (NO WARRANTY, etc. see website)

typedef struct { uint64_t state;  uint64_t inc; } pcg32_random_t;

uint32_t pcg32_random_r(pcg32_random_t* rng)
{
    uint64_t oldstate = rng->state;
    // Advance internal state
    rng->state = oldstate * 6364136223846793005ULL + (rng->inc|1);
    // Calculate output function (XSH RR), uses old state for max ILP
    uint32_t xorshifted = ((oldstate >> 18u) ^ oldstate) >> 27u;
    uint32_t rot = oldstate >> 59u;
    return (xorshifted >> rot) | (xorshifted << ((-rot) & 31));
}
```

and 

@techreport{oneill:pcg2014,
    title = "PCG: A Family of Simple Fast Space-Efficient Statistically Good Algorithms for Random Number Generation",
    author = "Melissa E. O'Neill",
    institution = "Harvey Mudd College",
    address = "Claremont, CA",
    number = "HMC-CS-2014-0905",
    year = "2014",
    month = Sep,
    xurl = "https://www.cs.hmc.edu/tr/hmc-cs-2014-0905.pdf",
}

Note that I found strange that it did not get published since 2014. I could not find a 

https://lemire.me/blog/2017/08/22/testing-non-cryptographic-random-number-generators-my-results/

2023-07-10 08:11 UTC, BastouP411 commented
> @TechReport{oneill:pcg2014,
> title = "PCG: A Family of Simple Fast Space-Efficient Statistically Good Algorithms for Random Number Generation",
> author = "Melissa E. O'Neill",
> institution = "Harvey Mudd College",
> address = "Claremont, CA",
> number = "HMC-CS-2014-0905",
> year = "2014",
> month = Sep,
> xurl = "https://www.cs.hmc.edu/tr/hmc-cs-2014-0905.pdf",
> }

Done :)

2023-07-10 08:22 UTC, svenvc commented
Correction for one link: https://www.pcg-random.org

I also like Wikipedia links: https://en.wikipedia.org/wiki/Permuted_congruential_generator

<blockquote><div>PCG, A Better Random Number Generator</div><div><strong><a href="http://www.pcg-random.org/index.html">PCG, A Family of Better Random Number Generators</a></strong></div><div>PCG is a family of simple fast space-efficient statistically good algorithms for random number generation.  Unlike many general-purpose RNGs, they are also hard to predict.</div></blockquote>
<blockquote><div><strong><a href="https://en.wikipedia.org/wiki/Permuted_congruential_generator">Permuted congruential generator - Wikipedia</a></strong></div></blockquote>

2023-07-10 08:39 UTC, svenvc commented
I am no specialist at all, and of course the implementation is an engineering tradeoff, but this critique seems rather harsh: https://pcg.di.unimi.it/pcg.php

2023-07-10 08:43 UTC, svenvc commented
> I am no specialist at all, and of course the implementation is an engineering tradeoff, but this critique seems rather harsh: https://pcg.di.unimi.it/pcg.php
> 
> > **[The wrap-up on PCG generators](https://pcg.di.unimi.it/pcg.php)**

Maybe it is all just noise, author's response to the critique: https://www.pcg-random.org/posts/on-vignas-pcg-critique.html

2023-07-11 13:44 UTC, guillep commented
I see that at the end this uses no primitive right?

Could you publish here a screenshot on how the new generator behaves in the case of the original issue?

Also, there seem to be a couple of failing tests, are they related?

<img width="813" alt="imagen" src="https://github.com/pharo-project/pharo/assets/708322/e1332ce6-8dec-4d4b-b6c9-5ea3a5c9dbca">

2023-07-13 16:51 UTC, Ducasse commented
tx sven for the two links. This was interesting (especially the answer).

2023-07-17 12:58 UTC, BastouP411 commented
> I see that at the end this uses no primitive right?

The primitive has not yet been implemented in the VM, the pull request is still out there.

> Could you publish here a screenshot on how the new generator behaves in the case of the original issue?

When running this:
```st
r := Random new.
((1 to: 10000) collect: [ :s | r seed: s. r next ]) rsHistogram 
```
We get something like this in the old random generator:
![broken_random](https://github.com/pharo-project/pharo/assets/28052007/b7d6d307-bf90-4c27-b09c-8ec152e32924)

The first generated from a new seed is highly biased (We only get numbers up to 0.08, and the limit is linear based on the seed.)

With the new generator, we do not have this bias:
![repaired_random](https://github.com/pharo-project/pharo/assets/28052007/77a6bb43-184b-4352-bfb9-5278f4308586)

2023-07-17 13:01 UTC, BastouP411 commented
Now only the Roassal tests fail, but they are unimportant and will be fixed shortly ( see https://github.com/ObjectProfile/Roassal3/pull/569 ) !

2023-07-27 08:20 UTC, merged