21207-Halo-description-is-almost-invisible-in-the-Help-browser
guillep/pharo-core pull request #1424
Opened 2018-05-25 14:12 UTC by oliveiraallex

Use yellow color for halo description. 

Fix case https://pharo.manuscript.com/f/cases/21207/Halo-description-is-almost-invisible-in-the-Help-browser

2018-05-25 18:13 UTC, rillig reviewed
I'd like to review this change, but I have deinstalled Pharo a few months ago. I tried to download the current development version Pharo 7 by following the instructions at https://pharo.org/contribute-report-bug and https://pharo.org/download, but there were no instructions. I could only download Pharo 6.1, but that's probably too old.

2018-05-28 14:07 UTC, jecisc requested changes

2018-05-28 14:07 UTC, jecisc commented on src/Morphic-Base/HaloMorph.class.st
> +	backgroundColor: self defaultBalloonColor;
This does not work with the dark theme.

I think it's better to do:
```Smalltalk
color: self theme balloonTextColor;
backgroundColor: self theme balloonBackgroundColor;
```

2018-06-12 09:17 UTC, jecisc commented
Ping?

2018-06-29 12:46 UTC, pavel-krivanek approved these changes

2018-06-29 13:59 UTC, jecisc approved these changes

2018-06-30 08:27 UTC, merged