Add FileLocator directories for music and video
guillep/pharo-core pull request #14532
Opened 2023-08-25 13:49 UTC by hernanmd

Add two locations to FileSystem library to locate the host system music and videos directories, as described in #4632.

Locations can be accessed through:

```smalltalk
FileLocator videos.
FileLocator music.
```

Add tests.

2023-08-25 14:39 UTC, jecisc approved these changes
Nice!

2023-08-25 14:45 UTC, astares commented
This PR will not work on Windows, there is no environment variable reflecting the music or video directory. 
Also CSIDL_COMMON_VIDEO is an id in C to access it via COM or Win32 API (CSIDL = "Constant Special Item ID List").

For instance once can use it with "SHGetFolderPath"  Win32 API function to find the folder path.

See #getWindowsFontFolderPath where this API is used for the font directory.

2023-08-25 14:47 UTC, astares requested changes
Will not work on Windows (see comment in PR)

2023-08-25 15:02 UTC, hernanmd commented
> The code
> 
> ```
>  self directoryFromEnvVariableNamed: 'CSIDL_COMMON_VIDEO'
> ```
> 
> can not work as CSIDL_COMMON_VIDEO is not a legal environment variable. So this will **not work on Windows** (see comment above)
> 
> In Windows 10/11 the path typically is
> 
> C:\Users<YourUsername>\Music C:\Users<YourUsername>\Videos
> 
> so you can construct it like
> 
> ```smalltalk
> (PlatformResolver forCurrentPlatform 
>   directoryFromEnvVariableNamed: 'USERPROFILE') / 'Videos'
> ```

Thanks for the feedback. I pused an update to use SHGetFolderPathA as you suggested.
I will check with a Windows box.

2023-08-25 19:47 UTC, Ducasse commented
So let us know when the PR is ready.

2023-09-13 15:06 UTC, jecisc commented
Hi @hernanmd , did you had the time to check by any chance?

2023-09-13 18:16 UTC, hernanmd commented
> Hi @hernanmd , did you had the time to check by any chance?

I will check tomorrow with the Windows box in the office and let you know.

2023-09-28 13:31 UTC, tesonep commented
This is an improvement but I have two comments:
1- We should use SHGetFolderPathW to handle wide characters in the path (You can see WinPlatform >> #getTempPath to see how it is better implemented)
2- We should use UFFI to perform the call, not using the backend directly. In the case of FT2 that is using it directly it is because it is used during the initialization of the image (maybe it should be pushed later when having UFFI loaded or it is somehting it is old, it does not have a lot of sense because FT2 uses UFFI)

2023-10-02 20:40 UTC, hernanmd commented
> This is an improvement but I have two comments: 1- We should use SHGetFolderPathW to handle wide characters in the path (You can see WinPlatform >> #getTempPath to see how it is better implemented) 2- We should use UFFI to perform the call, not using the backend directly. In the case of FT2 that is using it directly it is because it is used during the initialization of the image (maybe it should be pushed later when having UFFI loaded or it is somehting it is old, it does not have a lot of sense because FT2 uses UFFI)

I think by now we should use [SHGetKnownFolderPath](https://learn.microsoft.com/en-us/windows/win32/api/shlobj_core/nf-shlobj_core-shgetknownfolderpath) since SHGetFolderPathW was deprecated. I had a look and I wonder if in this case to pass the rfid as argument, one should use a FFIConstantHandle for the constant REFKNOWNFOLDERID?

2023-10-02 20:57 UTC, guillep commented
@tesonep @hernanmd There is no SHGetFolderPathW, the only version of this function accepts already wide strings as an out parameter seemingly. So yes, it needs to be decoded accordingly.

2023-10-02 21:02 UTC, guillep requested changes
This PR is far from ready.

Looking at the conflicts, I suggest this is redone from scratch.

2023-10-02 21:02 UTC, guillep commented on src/FileSystem-Core/WindowsResolver.class.st
> +	^ (buff copyFrom: 1 to: (buff indexOf: 0) - 1) asString
Yes, this is no way to go. We cannot accept this. Please, check the FFI booklet and use the standard way of doing FFI in Pharo please.

2023-10-02 21:02 UTC, guillep commented on src/FileSystem-Core/WindowsResolver.class.st
> +		       name: 'SHGetFolderPathA'
We should use the version without A as said in the comment by @hernanmd. And decode the wide string accordingly

2023-10-02 21:02 UTC, guillep commented on src/FileSystem-Core/WindowsResolver.class.st
> +		       name: 'SHGetFolderPathA'
Same as above.

Also, this is repeating all the code above with just an argument that changes.
This should be refactored in a single method with an argument.

2023-10-02 21:02 UTC, guillep commented on src/FileSystem-Core/WindowsResolver.class.st
> +	'cdefghijklmnopqrstuvwxyz' do: [ : drive |
This does not look well. Is this a standard way of doing this?

2023-10-02 21:02 UTC, guillep commented on src/FileSystem-Core/WindowsResolver.class.st
> +	'cdefghijklmnopqrstuvwxyz' do: [ : drive |
Same as above

2023-10-02 21:02 UTC, guillep commented on src/FileSystem-Core/WindowsResolver.class.st
> +	'cdefghijklmnopqrstuvwxyz' do: [ : drive |
Also, this code looks repeated.

2023-10-02 21:02 UTC, guillep commented on src/FileSystem-Tests-Core/FileLocatorTest.class.st
> +	self assert: locator resolve equals: FileLocator music resolve
What is the purpose of this test?

It's testing that x resolve = x resolve...?
The assertion does not make sense to me.

Maybe just a smoke test is enough?

2023-10-02 21:02 UTC, guillep commented on src/FileSystem-Tests-Core/FileLocatorTest.class.st
> +	self assert: locator resolve equals: FileLocator videos resolve
Same as above

2023-12-04 12:24 UTC, hernanmd commented on src/FileSystem-Core/WindowsResolver.class.st
> +	^ (buff copyFrom: 1 to: (buff indexOf: 0) - 1) asString
What's the real problem? (beyond being non-standard)

2023-12-04 13:06 UTC, guillep commented on src/FileSystem-Core/WindowsResolver.class.st
> +	^ (buff copyFrom: 1 to: (buff indexOf: 0) - 1) asString
Hi, this **is** a real problem. It's nonmaintainable and error-prone. Using the unified FFI framework this code gets 
- closer to the original C call (in the sense that it will be written and read similarly)
- the marshaling is done automatically by a framework that was designed to do so
- same for optimizations, object pinning...

2023-12-04 13:20 UTC, hernanmd commented on src/FileSystem-Core/WindowsResolver.class.st
> +	^ (buff copyFrom: 1 to: (buff indexOf: 0) - 1) asString
Again, why would I want to get closer to the original C call is there is an easier way to do it? In this case that would be also writing MORE code to get the [KNOWNFOLDERID](https://learn.microsoft.com/en-us/windows/win32/shell/knownfolderid) GUID, which I'm not interested at all. If I would have *another use case* for it, it is reasonable to invest in the translation.

At this stage I don't care if marshalling is done automatically by whom, and the same for optimizations. And asking for this type of stuff sounds like trying to force the same UFFI usage at all costs.

2023-12-04 13:26 UTC, guillep commented on src/FileSystem-Core/WindowsResolver.class.st
> +	^ (buff copyFrom: 1 to: (buff indexOf: 0) - 1) asString
I think we are not on the same page. Do you want to schedule a call?

2023-12-04 18:49 UTC, hernanmd commented on src/FileSystem-Core/WindowsResolver.class.st
> +	^ (buff copyFrom: 1 to: (buff indexOf: 0) - 1) asString
We could see it later since it is not urgent, thanks.

2023-12-06 07:54 UTC, Ducasse commented
Hi hernan

I should say that I do not like 
- your code
- your attitude

We do have to maintain code when people are moving to other horizons. 
So we CARE that the code is following our rules and frameworks. 
I do not even understand why we are discussing such obvious point. 

Guille is expert on FFI and he is dedicated to the improvement of Pharo. We should follow what he is saying. 
PERIOD. We should not make it lose his time. 

Sorry to be a be abrupt but I do not even understand why I have to make this point. 
So can you either close this PR or fix it?

2023-12-06 11:01 UTC, hernanmd commented
Thanks for the feedback. I would re doit from scratch, since I didn't took the right approach.
Let's check it later.

2023-12-06 11:01 UTC, closed without merging