ExternalAddress: Avoid temporary instance of ByteArray
guillep/pharo-core pull request #15404
Opened 2023-11-17 02:49 UTC by tinchodias

This change showed 2x speedup on my MacbookPro 2018.

Revealed by illimani-memory-profiler on Bloc benchmarks. See: https://github.com/pharo-graphics/Bloc/issues/322

@tesonep do you agree?

2023-11-17 11:06 UTC, MarcusDenker commented
Failing test not related

- [CI] Linux: OSEnvironmentTest fail with "Illegal continuation byte for utf-8 encoding" #13070

2023-11-17 21:59 UTC, tinchodias commented
Similar to #15405

2023-11-28 09:44 UTC, tesonep commented
It is good, the old one was to support big-endian and little-endian. We don't have big-endian platforms anymore. Maybe putting a comment to say that we only support little-endian

2023-11-28 09:46 UTC, tesonep requested changes
I will add a little comment saying that only works in little-endian platforms

2023-11-29 21:45 UTC, tinchodias commented
@tesonep please check if 4294a6c is fine

2023-12-01 15:19 UTC, merged