21795 - Subfolder with name "folder" gets deleted by test #testIssue6…
guillep/pharo-core pull request #1581
Opened 2018-06-23 15:23 UTC by carlotxra

…406 / FileDialog does not work with memory FileSystem

Fix https://pharo.fogbugz.com/f/cases/21795/Subfolder-with-name-folder-gets-deleted-by-test-testIssue6406-FileDialog-does-not-work-with-memory-FileSystem.

Fix FileDialogWindowTest to create and delete unique directory instead of a potential existing directory.
Add test and make changes to use memory FileSystem when using FileDialogWindow.
Many implicit references to Filesystem>>disk with methods like >>asFileReference etc.
Allow FileDialogWindow to handle root path.
Store the current instance of memory FileSystem so that a new one is not created on each call.

2018-06-23 21:27 UTC, carlotxra commented
Note that with these changes when we call FileSystem>>memory we answer with the current memory file system which in affect is a singleton (similar to how FileSystem>>disk works).
To create a new memory file system there is a method named FileSystem>>newMemory.

2018-06-23 21:28 UTC, carlotxra commented
This means that when using FileSystem>>memory we should treat it the same as if it was a disk io.e. clean up any files and directories in tests etc

2018-06-23 21:33 UTC, jecisc commented
I'm not sure it's a good idea to keep the same memory file system each time we call #memory. If we do that when do we garbage collect the files created in memory?

2018-06-24 21:06 UTC, carlotxra commented
Yes, you're right I was meant to register the MemoryStore to the startup list. We now will clear the in memory contents at startup.

2018-06-25 00:21 UTC, jecisc commented
This is a big change. I think we should maybe talk about it in the mailing list. Because for example, I work on seaside applications in which some files uploaded by the user are temporarily stored in the memory and in some deployment they are almost never restarted. If we are not aware of this we will have a memory leak.

2018-06-25 00:31 UTC, jecisc commented
Instead of changing #memory and adding a #newMemory, maybe we could keep the current #memory method as it is now and add a #currentMemoryFileSystem method keeping a singleton?

2018-06-25 04:10 UTC, VincentBlondeau requested changes
I agree with @jecisc. This should be discussed on the mailing list.

2018-06-25 05:26 UTC, astares commented
+1

2018-06-25 07:50 UTC, guillep commented
Hi, I skimmed the issue on the weekend but as soon as I saw the change of the semantics of `memory` and the addition of `newMemory` I said myself to wait for monday :).

What I'd suggest:
 - let's integrate everything except the modification of the `FileSystem>>memory` method. We can even integrate the new `FileSystem>>newMemory` without danger
 - then we can then discuss just THAT change in the mailing list

That would allow us to move forward, what do you think?

2018-06-25 20:24 UTC, carlotxra commented
Can I suggest we follow the suggestion by @jecisc which is what I would feel as more sensible for this use case. i.e. 

> Instead of changing #memory and adding a #newMemory, maybe we could keep the current #memory method as it is now and add a #currentMemoryFileSystem method keeping a singleton?

2018-06-25 20:53 UTC, carlotxra commented
I've made the changes so that the previous behaviour of #memory is put back. Added a method #currentMemoryFileSystem if users want to reference the same current memory filesystem instance (useful for any logic where need to reference the same filesystem).
Removed #newMemory.

2018-06-25 22:06 UTC, jecisc commented
Thank you! I think it's much easier for current users. 

Still, I would do it in two pull requests to make it easier to understand for people that do not follow closely the Pharo integrations.

2018-06-27 08:04 UTC, guillep commented on src/FileSystem-Memory/MemoryStore.class.st
> +]
This is strange... Why having a singleton if we are going to reset it every time we save the image?

2018-06-27 08:06 UTC, guillep approved these changes
Change is ok, we can iterate it afterwards.

I do not yet "swallow" the singleton memory filesystem but so far it does no harm.

2018-06-27 08:06 UTC, merged

2018-06-27 08:06 UTC, guillep commented
Thanks!