Deprecate explicitRequirement method
guillep/pharo-core pull request #16067
Opened 2024-01-29 17:14 UTC by hernanmd

As suggested in #15507, this method will be removed in future versions of Pharo.

2024-02-06 10:51 UTC, jordanmontt requested changes
Hello, you forgot to put it into the "Deprecated12" package.

2024-02-06 15:52 UTC, hernanmd commented
Done

2024-02-06 16:18 UTC, jordanmontt approved these changes

2024-03-05 13:01 UTC, closed without merging

2024-03-05 13:13 UTC, hernanmd commented
Now in #16277