Remove the package Deprecated12, introduce package Deprecated13
guillep/pharo-core pull request #16538
Opened 2024-04-27 18:07 UTC by pavel-krivanek

2024-04-28 12:45 UTC, jecisc commented
This causes a lot of tests to fail. Some of the deprecated code is still used

2024-04-28 14:19 UTC, astares commented
Would be good when the Deprecated13 package could be introduced nonetheless already.

2024-04-28 17:48 UTC, pavel-krivanek commented
We need to fix these tests in NewTools
NewTools.Scopes.Tests.ScopesTest.testClassScopeExcludesClassCreatedAPosteriori	2.7 sec	1
NewTools.Scopes.Tests.ScopesTest.testPackageScopeIncludesClassCreatedAPosteriori

2024-04-28 17:58 UTC, pavel-krivanek commented
https://github.com/pharo-spec/NewTools/pull/743

2024-04-28 18:10 UTC, pavel-krivanek commented
The `RSDependencyTest>>#testDependencies` seems to fail in the vanilla image as well, not a problem of this PR

2024-04-28 18:26 UTC, pavel-krivanek commented
and Roassal.Global.Tests.RSDependencyTest.testDependencies needs to be fixed in Roassal

2024-04-28 18:36 UTC, pavel-krivanek commented
https://github.com/pharo-graphics/Roassal/pull/63

2024-04-28 18:37 UTC, pavel-krivanek commented
God save integrators :-)

2024-05-14 21:55 UTC, astares commented
One dependency is nuked with https://github.com/pharo-project/pharo/pull/16657

2024-05-15 09:28 UTC, jecisc commented
Tests failures are down to 4

<a onclick="showFailureSummary('test-Unix64.ReleaseTests/ProperPackagesTest/unix_64___Tests_unix_64___testProperManifestCategorization/','Unix64.ReleaseTests/ProperPackagesTest/unix_64___Tests_unix_64___testProperManifestCategorization//summary')" id="test-Unix64.ReleaseTests/ProperPackagesTest/unix_64___Tests_unix_64___testProperManifestCategorization/-showlink" title="Show details"><svg class="icon-sm" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"></svg></a>
unix-64 / Tests-unix-64 / Unix64.ReleaseTests.ProperPackagesTest.testProperManifestCategorization | 0.34 sec | 1
-- | -- | --
 

 <a href="https://ci.inria.fr/pharo-ci-jenkins2/job/Test%20pending%20pull%20request%20and%20branch%20Pipeline/job/PR-16538/4/testReport/Unix64.UnifiedFFI.Tests/FFIAutoReleaseOptionCalloutTest/unix_64___Tests_unix_64___testVoidPointer/">unix-64 / Tests-unix-64 / Unix64.UnifiedFFI.Tests.FFIAutoReleaseOptionCalloutTest.testVoidPointer</a>[unix-64 / Tests-unix-64 / Unix64.ReleaseTests.ProperPackagesTest.testProperManifestCategorization](https://ci.inria.fr/pharo-ci-jenkins2/job/Test%20pending%20pull%20request%20and%20branch%20Pipeline/job/PR-16538/4/testReport/Unix64.ReleaseTests/ProperPackagesTest/unix_64___Tests_unix_64___testProperManifestCategorization/)	0.34 sec	[1](https://ci.inria.fr/pharo-ci-jenkins2/job/Test%20pending%20pull%20request%20and%20branch%20Pipeline/job/PR-16538/4/)
 [unix-64 / Tests-unix-64 / Unix64.ReleaseTests.ReleaseTest.testThatThereAreNoSelectorsRemainingThatAreSentButNotImplemented](https://ci.inria.fr/pharo-ci-jenkins2/job/Test%20pending%20pull%20request%20and%20branch%20Pipeline/job/PR-16538/4/testReport/Unix64.ReleaseTests/ReleaseTest/unix_64___Tests_unix_64___testThatThereAreNoSelectorsRemainingThatAreSentButNotImplemented/)	1.2 sec	[1](https://ci.inria.fr/pharo-ci-jenkins2/job/Test%20pending%20pull%20request%20and%20branch%20Pipeline/job/PR-16538/4/)
 [unix-64 / Tests-unix-64 / Unix64.UnifiedFFI.Tests.FFIAutoReleaseOptionCalloutTest.testExternalStructure](https://ci.inria.fr/pharo-ci-jenkins2/job/Test%20pending%20pull%20request%20and%20branch%20Pipeline/job/PR-16538/4/testReport/Unix64.UnifiedFFI.Tests/FFIAutoReleaseOptionCalloutTest/unix_64___Tests_unix_64___testExternalStructure/)	8.6 sec	[1](https://ci.inria.fr/pharo-ci-jenkins2/job/Test%20pending%20pull%20request%20and%20branch%20Pipeline/job/PR-16538/4/)
 [unix-64 / Tests-unix-64 / Unix64.UnifiedFFI.Tests.FFIAutoReleaseOptionCalloutTest.testVoidPointer](https://ci.inria.fr/pharo-ci-jenkins2/job/Test%20pending%20pull%20request%20and%20branch%20Pipeline/job/PR-16538/4/testReport/Unix64.UnifiedFFI.Tests/FFIAutoReleaseOptionCalloutTest/unix_64___Tests_unix_64___testVoidPointer/)

2024-05-15 12:52 UTC, jecisc commented
Fixing multiple calls to deprecated methods here: https://github.com/pharo-spec/NewTools/pull/749

2024-05-15 12:56 UTC, jecisc commented
And here another one: https://github.com/pharo-project/pharo/pull/16658

2024-05-15 12:57 UTC, jecisc requested changes
Requesting a change to fix one of the failing tests

2024-05-15 12:57 UTC, jecisc commented on src/Deprecated13/ManifestDeprecated13.class.st
> +	#package : 'Deprecated13'
```suggestion
	#package : 'Deprecated13',
	#tag: 'Manifest'
```

2024-05-16 12:07 UTC, jecisc commented
There is only one failure left that should be fixed with a PR I did to Pharo soon!

2024-05-16 13:39 UTC, jecisc approved these changes

2024-05-16 13:39 UTC, merged