proposition refactoring -> Cleanup: 2 duplicated methods in FreeType
guillep/pharo-core pull request #16583
Opened 2024-05-06 09:49 UTC by AngelHely

This pull request proposes a refactoring for : 

-     EmbeddedFreeTypeFontInstaller>>#addFromFileContents:baseName:
-     FreeTypeFontProvider>>#updateFromFile:

pull request proposed by @demarey @DurieuxPol and me 

#15265

2024-05-07 06:47 UTC, MarcusDenker commented
Builds fails with

```
Instance of FreeTypeFontProvider did not understand #validEmbeddedCachedInfoFor:index:
FreeTypeFontProvider(Object)>>doesNotUnderstand: #validEmbeddedCachedInfoFor:index:
FreeTypeFontFileUpdator(AbstractFreeTypeFontFile)>>cachedNumFacesFromData:
FreeTypeFontFileUpdator>>updateFromFile:
```

2024-05-07 20:20 UTC, jecisc requested changes

2024-05-07 20:20 UTC, jecisc commented on src/EmbeddedFreeType/FreeTypeFontFileUpdator.class.st
> +FreeTypeFontFileUpdator >> failedToOpen: face from: path index: i [
The superclass has an instance variable called 'face'. Thus, this name cannot be used here and another name should be used.

2024-05-07 20:20 UTC, jecisc commented on src/EmbeddedFreeType/FreeTypeFontFileInstaller.class.st
> +	index < numFaces ] whileTrue: [  ]
I guess #whileTrue could be used instead of #whileTrue:?

2024-05-07 20:20 UTC, jecisc commented on src/EmbeddedFreeType/FreeTypeFontFileInstaller.class.st
> +FreeTypeFontFileInstaller >> failedToOpen: face index: index [
Same comment about the parameter #face conflicting with instance variable name

2024-05-13 11:46 UTC, jecisc approved these changes

2024-05-13 11:46 UTC, merged