Fix multiple tests with refactoring driver for duplicate class.
guillep/pharo-core pull request #16853
Opened 2024-07-02 12:59 UTC by hernanmd

Fix a couple of tests failing, reported in #16850, due to missing support to pre-configure refactorings for test purposes.
Also configured missing mocks for the preview presenter.

2024-07-02 13:03 UTC, MarcusDenker commented
Argh, I did merge the revert in the meantime so now this is a conflict.

2024-07-02 13:07 UTC, MarcusDenker commented
I am doing a revert of the revert: https://github.com/pharo-project/pharo/pull/16854

2024-07-02 13:12 UTC, hernanmd commented
> I am doing a revert of the revert: #16854

Thanks, I will check further fails and check better next time.
(and I forgot to mention I was working on this issue)

2024-07-02 14:33 UTC, MarcusDenker commented
Revert fixed the conflicts, tests are now run

2024-07-02 15:34 UTC, MarcusDenker commented on src/Refactoring-UI/ReDuplicateClassDriver.class.st
> +{ #category : 'as yet unclassified' }
this makes testNoUncategorizedMethods fail

2024-07-02 15:35 UTC, MarcusDenker requested changes
this adds one more failing testNoUncategorizedMethods

2024-07-03 06:45 UTC, MarcusDenker commented on src/Refactoring-Core/RBCopyClassRefactoring.class.st
> +||||||| 3926c07db6:src/Refactoring-Core/ReCopyClassRefactoring.class.st
this is now leading to load error

```
MetacelloNotification: Loaded -> Refactoring-Environment --- tonel:///builds/workspace/est_and_branch_Pipeline_PR-16853/64/src()
MetacelloNotification: Loaded -> Refactoring-Changes --- tonel:///builds/workspace/est_and_branch_Pipeline_PR-16853/64/src()
TonelParseError: Can't parse method body
```

2024-07-03 12:05 UTC, MarcusDenker commented
Now load fails:

```
MetacelloNotification: Loaded -> Refactoring-Changes --- tonel:///builds/workspace/est_and_branch_Pipeline_PR-16853/64/src()
Error: Package Refactoring-Core depends on the following classes:
  ReCopyClassRefactoring
You must resolve these dependencies before you will be able to load these definitions: 
  ReCopyClassRefactoring>>#classMethods
  ReCopyClassRefactoring>>#classMethods:
  ReCopyClassRefactoring>>#copyClass
  ReCopyClassRefactoring>>#copyClass:withName:
  ReCopyClassRefactoring>>#copyMethods:of:in:
  ReCopyClassRefactoring>>#instanceMethods

```

2024-07-04 06:56 UTC, MarcusDenker commented
Now all the test that the revert fixed are failing:

```

ReDuplicateClassDriverTest.testDuplicateClass	
 
 
 osx-64 / Tests-osx-64 / MacOSX64.Refactoring.Transformations.Tests.RBCopyPackageParametrizedTest.testCopyPackageAndChangesCopyReferences(#rbClass->RBCopyPackageRefactoring)	6.8 sec	1
 osx-64 / Tests-osx-64 / MacOSX64.Refactoring.Transformations.Tests.RBCopyPackageParametrizedTest.testCopyPackageWithParameters(#rbClass->RBCopyPackageRefactoring)
```

In addition, we have:

ReleaseTest>>testUndeclared


It might fix other, but honestly, I am starting to get lost completely

Might it not be a better idea to revert ?

2024-07-04 07:00 UTC, guillep commented
Hi Marcus, I agree with you. We should revert. That was the rule we set.

@hernanmd it is important for us that this gets fixed fast, either by reverting or by fixing it.
It simplifies the management of all the other ~60 PRs we have.

2024-07-04 16:17 UTC, hernanmd commented
> this adds one more failing testNoUncategorizedMethods

Hi @MarcusDenker, could you share a link to see the failed tests?

2024-07-05 07:52 UTC, MarcusDenker commented
The failing tests are here:

https://ci.inria.fr/pharo-ci-jenkins2/job/Test%20pending%20pull%20request%20and%20branch%20Pipeline/job/PR-16853/8/testReport/

2024-07-05 11:35 UTC, MarcusDenker approved these changes

2024-07-05 11:35 UTC, MarcusDenker commented
Thanks!

2024-07-05 11:35 UTC, merged