Extract temp
guillep/pharo-core pull request #17153
Opened 2024-09-23 12:15 UTC by SandraSamardzic

Migrate extract temp to new architecture

2024-09-23 12:22 UTC, balsa-sarenac requested changes
Nice work, just a minor comment. If you decide on creating a condition for checking if selection is a sequence, please do include tests for it, if not, we will deal with it in a latter PR.

2024-09-23 12:22 UTC, balsa-sarenac commented on src/Refactoring-Core/RBExtractToTemporaryRefactoring.class.st
> +			   		self checkVariableName.
Would it make sense to create condition classes for these two conditions as well?
- `verifySelectedInterval` just checks if the selection is a sequence,
- `checkVariableName` should be already defined as a condition.
I suggest at least to inline `verifySelectedInterval` and add `ReCheckVariableName` to the list of preconditions.

2024-09-24 18:04 UTC, Ducasse commented
Thanks sandra 
This is really great to see all these enhancements.

2024-09-24 18:05 UTC, Ducasse commented
I see that the following test is not passing 

[osx-64 / Tests-osx-64 / MacOSX64.Refactoring.Core.Tests.ReMethodsHaveNoDuplicatesTest.testMethodDuplicatedInSibling](https://ci.inria.fr/pharo-ci-jenkins2/job/Test%20pending%20pull%20request%20and%20branch%20Pipeline/job/PR-17153/2/testReport/junit/MacOSX64.Refactoring.Core.Tests/ReMethodsHaveNoDuplicatesTest/osx_64___Tests_osx_64___testMethodDuplicatedInSibling/)

2024-09-24 18:42 UTC, SandraSamardzic commented
Thank you @Ducasse, I am trying my best. I did see that the test didn't pass but I don't see where is the test nor where is the problem...

2024-09-25 08:51 UTC, Ducasse commented
I will integrate and we can see. 
You cannot find `ReMethodsHaveNoDuplicatesTest >> testMethodDuplicatedInSibling`

2024-09-25 09:55 UTC, balsa-sarenac commented
@Ducasse I think she couldn't find failing tests in the CI. I'll send her a message with some instructions

2024-09-26 08:51 UTC, balsa-sarenac commented
@Ducasse I think that failing test is from Caro's PR, this can be merged

2024-09-26 08:51 UTC, balsa-sarenac approved these changes

2024-09-26 08:52 UTC, merged