add classNamed: in BaselineOf
guillep/pharo-core pull request #17360
Opened 2024-11-10 17:59 UTC by Ducasse

use classNamed: where needed.
Should do Spec2 and NewTools baselines too.

2024-11-11 14:38 UTC, Ducasse commented
I will add first classNamed: alone because there may be some dependencies.

2024-11-11 16:17 UTC, Ducasse commented
Let us now that the baselineOf new behavior has been added in another PR if this one is still not building.

2024-11-12 10:39 UTC, jecisc commented
There seems to be a problem with this change:

Instance of SystemEnvironment did not understand #specialObjectsArray
SystemEnvironment(Object)>>doesNotUnderstand: #specialObjectsArray
BaselineOfDisplay>>installBitmap
BaselineOfDisplay>>postload:package:

2024-11-12 17:27 UTC, jecisc requested changes

2024-11-12 17:27 UTC, jecisc commented on src/BaselineOfDisplay/BaselineOfDisplay.class.st
> +	array := self class environment specialObjectsArray copy.
It's not the environment that knows the special object array but the image

2024-11-12 17:27 UTC, jecisc commented on src/BaselineOfDisplay/BaselineOfDisplay.class.st
> +	self class environment specialObjectsArray becomeForward: array.
Same

2024-11-12 17:27 UTC, jecisc commented on src/BaselineOfIDE/BaselineOfIDE.class.st
> +	os := self class environment os.
We should use `self os` since it's now in BaselineOf

2024-11-12 19:22 UTC, Ducasse commented on src/BaselineOfDisplay/BaselineOfDisplay.class.st
> +	array := self class environment specialObjectsArray copy.
Yes my mistake I will redo this PR.

2024-11-12 19:22 UTC, Ducasse commented on src/BaselineOfIDE/BaselineOfIDE.class.st
> +	os := self class environment os.
Yes!

2024-11-12 19:22 UTC, closed without merging