22534-split-Refactoring2-package-to-extract-Tests
guillep/pharo-core pull request #1871
Opened 2018-10-05 12:02 UTC by estebanlm

https://pharo.manuscript.com/f/cases/22534/split-Refactoring2-package-to-extract-Tests

2018-10-05 12:42 UTC, jecisc requested changes

2018-10-05 12:42 UTC, jecisc commented on src/BaselineOfIDE/BaselineOfIDE.class.st
> +		spec package: 'Refactoring2-Transformations-Tests'.
I think it also needs to be in the groups.

2018-10-05 13:36 UTC, pavel-krivanek commented
and failing SystemDependenciesTest

2018-10-05 14:11 UTC, estebanlm commented
why? it is related?

2018-10-09 10:30 UTC, estebanlm commented
so? @pavel-krivanek can I integrate this?

2018-10-09 12:28 UTC, pavel-krivanek commented
yes

2018-10-09 12:29 UTC, merged