20930-Methods-using-printString-asString--or-storeString-in-printOnstoreOn
guillep/pharo-core pull request #2114
Opened 2018-12-21 14:13 UTC by Ducasse

redo and fix some of the change of badetitou

2018-12-21 14:26 UTC, svenvc commented
I haven't  checked them all in details, but yes this make sense

2018-12-21 15:02 UTC, jecisc requested changes

2018-12-21 15:02 UTC, jecisc commented on src/EmbeddedFreeType/FreeTypeEmbeddedFileInfo.class.st
> +			nextPut: '{';
```suggestion
 			nextPut: ${;
```

2018-12-21 15:02 UTC, jecisc commented on src/EmbeddedFreeType/FreeTypeEmbeddedFileInfo.class.st
> +			nextPut: '}';
```suggestion
 			nextPut: $};
```

2018-12-21 15:02 UTC, jecisc commented on src/EmbeddedFreeType/FreeTypeEmbeddedFileInfo.class.st
> +			nextPut: '(';
```suggestion
 			nextPut: $(;
```

2018-12-21 15:02 UTC, jecisc commented on src/EmbeddedFreeType/FreeTypeEmbeddedFileInfo.class.st
> +			nextPut: '[';
```suggestion
 			nextPut: $[;
```

2018-12-21 15:02 UTC, jecisc commented on src/EmbeddedFreeType/FreeTypeEmbeddedFileInfo.class.st
> +			nextPutAll: ' ';
```suggestion
 			space;
```

2018-12-21 15:02 UTC, jecisc commented on src/EmbeddedFreeType/FreeTypeEmbeddedFileInfo.class.st
> +			nextPutAll: ' ';
```suggestion
 			space;
```

2018-12-21 15:02 UTC, jecisc commented on src/EmbeddedFreeType/FreeTypeEmbeddedFileInfo.class.st
> +			nextPutAll: ' ';
```suggestion
 			space;
```

2018-12-21 15:02 UTC, jecisc commented on src/EmbeddedFreeType/FreeTypeEmbeddedFileInfo.class.st
> +			nextPutAll: ' ';
```suggestion
 			space;
```

2018-12-21 15:02 UTC, jecisc commented on src/EmbeddedFreeType/FreeTypeEmbeddedFileInfo.class.st
> +			nextPutAll: ' ';
```suggestion
 			space;
```

2018-12-21 15:02 UTC, jecisc commented on src/Monticello/MCWorkingCopy.class.st
> +										nextPutAll: '(' ;
```suggestion
 										nextPut: $( ; 
```

2018-12-21 15:02 UTC, jecisc commented on src/Monticello/MCWorkingCopy.class.st
> +										nextPutAll: ')']
```suggestion
 										nextPut: $)]
```

2018-12-21 15:02 UTC, jecisc commented on src/Morphic-Base/HaloSpec.class.st
> +		nextPutAll: ' ';
```suggestion
 		space;
```

2018-12-21 15:02 UTC, jecisc commented on src/Morphic-Base/HaloSpec.class.st
> +		nextPutAll: ')'
```suggestion
 		nextPut: $)
```

2018-12-21 15:02 UTC, jecisc commented on src/NECompletion/SHRange.class.st
> +		nextPutAll: ' ';
```suggestion
 		space;
```

2018-12-21 15:02 UTC, jecisc commented on src/NECompletion/SHRange.class.st
> +		nextPutAll: ']'
```suggestion
 		nextPut: $]
```

2018-12-21 15:19 UTC, merged

2018-12-22 08:45 UTC, MarcusDenker commented
it seems now we have lots of failing test in the released image

2018-12-22 08:46 UTC, MarcusDenker commented
unix-32 / Tests-unix-32 / Unix32.FileSystem.Tests.Core.Base.PathTest.testRelativePrintString | 5 ms | 3
unix-32 / Tests-unix-32 / Unix32.Kernel.Tests.Extended.Classes.ClassTest.testAddClassSlot | 97 ms | 3
unix-32 / Tests-unix-32 / Unix32.NECompletion.Tests.NECEntryTest.testPrintOn | 9 ms | 3
unix-32 / Tests-unix-32 / Unix32.Refactoring.Tests.Core.RBRefactoringTest.testConditions | 14 ms | 3
unix-32 / Tests-unix-32 / Unix32.Slot.Tests.SlotClassVariableTest.testSlotIsPersistedAfterRebuildOfClass | 0.1 sec | 3
unix-32 / Tests-unix-32 / Unix32.Slot.Tests.SlotClassVariableTest.testAccessorInstanceVariableSlotGeneratesAccessors

2018-12-22 08:47 UTC, MarcusDenker commented
maybe not all due to this but the printOn: looks related