2587-Cannot-remove-a-Trait
guillep/pharo-core pull request #2721
Opened 2019-02-25 10:45 UTC by tesonep

When Calypso removes a Trait it uses the refactoring browser. As RB is not prepared for stateful traits I have to extend it. 
Also I have improved the detection of subclasses.

2019-02-25 14:21 UTC, jecisc requested changes
I suggested a change.

2019-02-25 14:21 UTC, jecisc commented on src/Kernel/Class.class.st
> +	^ self subclasses isEmpty not
```suggestion
	^ self subclasses isNotEmpty
```

2019-03-01 13:00 UTC, MarcusDenker commented
I propose to merge this now and improve later

2019-03-01 14:18 UTC, MarcusDenker commented
(because I do not find how to accept that change even after assigning the issue to me)

2019-03-01 14:18 UTC, merged