2938 - Fixing FFIConstantHandleType externalType wrong in 64 bit
guillep/pharo-core pull request #2940
Opened 2019-03-20 18:40 UTC by StephanEggermont

Getting inspired by the nice code that was written in squeak monticello repository.
Thx @eliotmiranda and @VincentBlondeau and @astares ! 

I.e.:

FFI-Kernel-eem.57
Time: 6 November 2018, 6:39:32 pm

Provide the longLong to complement the set of other integer conveniences.

FFI-Kernel-eem.55
Time: 23 August 2018, 2:12:03 pm

Add an errorCode to ExternalFunction>>invokeWithArguments:.  At least for now the design for the catching of exceptions during FFI calls has failing the callout on exception enabled by the callout having an error code.

FFI-Kernel-nice.52
Time: 29 April 2018, 6:39:52 pm

Fix pointerSpec for 64bits FFI
A pointer has a Smalltalk wordSize byte-length, rather than hardcoded 4 byte length.

FFI-Kernel-nice.49
Time: 13 April 2018, 3:56:28 pm

Give a chance to recompile the structure compiledSpec when resuming on a different platform. See ExternalStructure class>>#install.

FFI-Kernel-nice.48
Time: 13 April 2018, 8:00:08 am

Correct a bug for 64bits pointer arithmetic: unsignedLongAt: and unsignedLongAt:put: are not machine dependent, they allways fetch/store an uint32_t

No need to invoke self class wordSize, when self size already encodes the same information.

2019-03-20 18:40 UTC, StephanEggermont commented
Fixes #2938

2019-03-20 18:41 UTC, StephanEggermont commented
Needs backport

2019-03-21 13:28 UTC, estebanlm requested changes
mmm. while I agree this changes are useful, the right fix in FFIConstantHandleType is not to hack about the length of long, but to consider them a datatype of the same size of a pointer (which is what they are). 
Also, this harvested changes overrides some categorisations/comments we made, so it needs to be made more carefully.

2019-03-22 09:35 UTC, VincentBlondeau commented
Tests that are failing:

```
Nouveaux échecs - 5
windows-32 / Tests-windows-32 / testImageContainsOneSubscribedOrganizer – Windows32.RPackage.Tests.RPackageWithDoTest<1s
windows-32 / Tests-windows-32 / testAliasCompositions – Windows32.Tests.Traits.TraitCompositionTest<1s
windows-32 / Tests-windows-32 / testSumWithParenthesis – Windows32.Tests.Traits.TraitCompositionTest<1s
osx-32 / Tests-osx-32 / testImageContainsOneSubscribedOrganizer – MacOSX32.RPackage.Tests.RPackageWithDoTest<1s
osx-32 / Tests-osx-32 / testAliasCompositions – MacOSX32.Tests.Traits.TraitCompositionTest<1s
Échecs préexistant - 6
windows-32 / Tests-windows-32 / testImageContainsOneSubscribedOrganizer – Windows32.RPackage.Tests.RPackageWithDoTest<1s
windows-32 / Tests-windows-32 / testAliasCompositions – Windows32.Tests.Traits.TraitCompositionTest<1s
windows-32 / Tests-windows-32 / testSumWithParenthesis – Windows32.Tests.Traits.TraitCompositionTest<1s
osx-32 / Tests-osx-32 / testImageContainsOneSubscribedOrganizer – MacOSX32.RPackage.Tests.RPackageWithDoTest<1s
osx-32 / Tests-osx-32 / testAliasCompositions – MacOSX32.Tests.Traits.TraitCompositionTest<1s
unix-32 / Tests-unix-32 / testChangeWidgetTextUpdatesPresenter – Unix32.Spec.MorphicBackendTests.MorphicTextInputFieldAdapterTest<1s
unix-32 / Tests-unix-32 / testMaxLengthIsSetInWidget – Unix32.Spec.MorphicBackendTests.MorphicTextInputFieldAdapterTest<1s
windows-32 / Tests-windows-32 / testChangeWidgetTextUpdatesPresenter – Windows32.Spec.MorphicBackendTests.MorphicTextInputFieldAdapterTest<1s
windows-32 / Tests-windows-32 / testMaxLengthIsSetInWidget – Windows32.Spec.MorphicBackendTests.MorphicTextInputFieldAdapterTest<1s
osx-32 / Tests-osx-32 / testChangeWidgetTextUpdatesPresenter – MacOSX32.Spec.MorphicBackendTests.MorphicTextInputFieldAdapterTest<1s
osx-32 / Tests-osx-32 / testMaxLengthIsSetInWidget – MacOSX32.Spec.MorphicBackendTests.MorphicTextInputFieldAdapterTest
```

2019-03-26 09:59 UTC, VincentBlondeau commented
The failures are not related to the issue.

2019-03-26 21:26 UTC, estebanlm commented
let me see the CI again

2019-04-02 13:09 UTC, guillep commented
Same comment as in https://github.com/pharo-project/pharo/pull/2945

> Overall, harvesting the changes is good, but still I do not understand how they actually fix the original bug with FFIConstantHandleType. I am reading now
> 
> ```smalltalk
> FFIConstantHandleType >> externalType
> 	^ ExternalType ulong
> ```
> And I wonder: in windows HANDLEs are just pointers, why not redefine that as
> 
> ```smalltalk
> FFIConstantHandleType >> externalType
> 	^ ExternalType void asPointer
> ```
> ?
> 
> That would make much much clearer the intention.
> In any case, making that change without harvesting the changes seems futile because this seems buggy in the current version. In 64 bits I get:
> 
> ```smalltalk
> ExternalType void asPointerType byteSize => 4
> ```
> !!!

I understand that HANDLEs in windows are "integer like" but they are and they work as pointers. Making them integers does not help in anything but pretty printing. Actually it's the other way around, it complicates the calculation of types and sizes and makes people more confused...

I've been in the couple of months playing with different windows APIs and treating HANDLEs as pointers works just fine and produces no further trouble.

Maybe @tesonep has something to add...

2019-04-13 13:49 UTC, StephanEggermont commented
I'm unsure about the next steps

2019-04-14 05:56 UTC, estebanlm commented
let see how the build goes now :)

2019-04-15 13:53 UTC, guillep commented
@StephanEggermont I've overseen this PR before because the state was still in "requested changes", something related to categorizations. Is that important or not? @estebanlm ?

2019-04-15 14:23 UTC, StephanEggermont commented
I fixed the categorizations. The other parts I’m confused about

2019-04-17 14:49 UTC, estebanlm commented
what other parts?
It seems that is ok... this symbol to decide when regenerate looks bad, but is like that in FFI-Kernel :(

2019-04-19 11:05 UTC, estebanlm commented
I will try to integrate this, but I do not like the failing tests. Running again :)

2019-04-24 13:29 UTC, estebanlm commented on src/Spec-Core/MenuItemPresenter.class.st
>  MenuItemPresenter >> performMenuActionWith: aMenuItem [
why there is this change here?

2019-05-06 08:01 UTC, estebanlm commented
Still, I don't know what `MenuItemPresenter` is doing in this PR :)

2019-05-06 08:02 UTC, VincentBlondeau commented
@estebanlm That is why I created a new one without.

2019-05-06 08:29 UTC, VincentBlondeau commented
See https://github.com/pharo-project/pharo/pull/3252

2019-05-06 09:16 UTC, estebanlm commented
So we close this one :)

2019-05-06 09:16 UTC, closed without merging