Adding <debuggerCompleteToSender> pragma to some assert methods so th…
guillep/pharo-core pull request #3008
Opened 2019-03-25 09:51 UTC by dupriezt

…at the debugger opens directly on the failing test method when a test fails.

Fixes #3006

2019-03-25 12:16 UTC, MarcusDenker commented
I will reopen to run with the latest tests...

2019-03-28 06:45 UTC, akgrant43 requested changes
Hi @dupriezt 

I like this change, but there are multiple methods where it also should be added (actually I'm not sure how this ever worked for Object>>assert: since #assert: calls #assert:description:, which is missing the pragma, thus the debugger opens in #assert:description:):

- Object>>assert:description:
- All the methods in TestAsserter asserting protocol

Cheers,
Alistair

2019-03-29 18:58 UTC, akevalion commented
I have added the the pragma <debuggerCompleteToSender> check the PR https://github.com/pharo-project/pharo/pull/3108

2019-03-30 07:22 UTC, MarcusDenker commented
doing things in parallel is often quite confusing. It is better to review the other and push to have it integrated *or* create one shared PR.

2019-04-01 07:43 UTC, dupriezt commented
Closing this since PR #3116 encompasses its changes.

2019-04-01 07:43 UTC, closed without merging