Issue/3030
guillep/pharo-core pull request #3121
Opened 2019-04-01 08:57 UTC by Alisu

introduce 
 - ClassParser
 - ClassDefinition
 - UndefinedClasses

Integrate them with ClassBuilder (optional and off by default)
Update SugsSuggestions with new nodes

All with tests

2019-04-01 09:00 UTC, MarcusDenker commented
we really need to carefully review this PR. the last had really odd side effects. e.g. it made class builder tests fail.

2019-04-01 09:05 UTC, guillep commented
Hi Marcus, I'm taking care of it, please do not stress :)

2019-04-01 13:15 UTC, guillep commented
The build now finishes ok, except for some failing tests. These remaining tests are

![image](https://user-images.githubusercontent.com/708322/55330293-f2615680-5490-11e9-91ee-bd9fe426f465.png)

Are they some flaky tests?

2019-04-01 13:18 UTC, MarcusDenker commented
The announcer test fails all couple of build. no idea why (see #2471) The testMaxLengthIsSetInWidget falls consistently (not related to the changes in this issue). I added https://github.com/pharo-project/pharo/issues/3119 for that.

2019-04-02 12:04 UTC, guillep requested changes

2019-04-02 12:04 UTC, guillep commented on src/ClassParser/ShiftClassBuilder.extension.st
> +|package|
Could you format this method ? It really does not follow any convention. See below

2019-04-02 12:04 UTC, guillep commented on src/ClassParser/ShiftClassBuilder.extension.st
> +	ifTrue:[self superclass: nil].
Here again

2019-04-02 12:04 UTC, guillep commented on src/ClassParser/ShiftClassBuilder.extension.st
> +	aCDClassDefinitionNode packageName ifNotNil:[:cat | package:= cat] ifNil:[package:= 'Unclassified'].
Here again

2019-04-02 12:04 UTC, guillep commented on src/ClassParser/ShiftClassBuilder.extension.st
> +	evaluate)].
What is that line commented?

2019-04-10 08:02 UTC, guillep commented
Thanks Theo!

2019-04-10 08:02 UTC, merged