3662-Reify-type-of-test-results
guillep/pharo-core pull request #3666
Opened 2019-06-27 13:48 UTC by juliendelplanque

Experiment to fix #3662

2019-06-27 16:08 UTC, jecisc requested changes

2019-06-27 16:08 UTC, jecisc commented on src/SUnit-Core/ClassFactoryForTestCase.class.st
> +ClassFactoryForTestCase >> newTraitUsing: aTraitComposition [.
```suggestion
ClassFactoryForTestCase >> newTraitUsing: aTraitComposition [
```

2019-06-27 16:08 UTC, jecisc commented on src/SUnit-Core/TestAsserter.class.st
> -TestAsserter >> assert: actualNumber closeTo: expectedNumber precision: margin [
Are those removals wanted?

2019-06-27 16:08 UTC, jecisc commented on src/SUnit-Core/TestFailed.class.st
> +TestFailed >> color [
It could be an extension of SUnit-UI?

2019-06-27 16:40 UTC, juliendelplanque commented on src/SUnit-Core/TestAsserter.class.st
> -TestAsserter >> assert: actualNumber closeTo: expectedNumber precision: margin [
Hum, no I do not know what happened I will check.

2019-06-27 16:41 UTC, juliendelplanque commented on src/SUnit-Core/ClassFactoryForTestCase.class.st
> +ClassFactoryForTestCase >> newTraitUsing: aTraitComposition [.
What is that? I did not touch this.

2019-06-27 16:42 UTC, juliendelplanque commented on src/SUnit-Core/TestFailed.class.st
> +TestFailed >> color [
Yes I think as well.

2019-06-27 16:45 UTC, jecisc commented on src/SUnit-Core/ClassFactoryForTestCase.class.st
> +ClassFactoryForTestCase >> newTraitUsing: aTraitComposition [.
It is probably a fix in Iceberg. When you commit it export the whole package.

2019-06-27 16:46 UTC, juliendelplanque commented on src/SUnit-Core/ClassFactoryForTestCase.class.st
> +ClassFactoryForTestCase >> newTraitUsing: aTraitComposition [.
Ok I commit that.

2019-06-27 16:49 UTC, ErikOnBike commented on src/SUnit-Core/TestAsserter.class.st
> -TestAsserter >> assert: actualNumber closeTo: expectedNumber precision: margin [
FYI: I had exactly the same issue (same changes I did not make myself) when I updated something in the SUnit-Core package (see #3583).

2019-06-27 16:50 UTC, ErikOnBike commented on src/SUnit-Core/TestAsserter.class.st
> -TestAsserter >> assert: actualNumber closeTo: expectedNumber precision: margin [
BTW: My solution was to manually restore things through git directly on the filesystem instead of the through the Smalltalk image.

2019-06-27 16:50 UTC, juliendelplanque commented on src/SUnit-Core/TestAsserter.class.st
> -TestAsserter >> assert: actualNumber closeTo: expectedNumber precision: margin [
Thank you! I will revert these changes.

2019-06-27 17:03 UTC, juliendelplanque commented on src/SUnit-Core/TestAsserter.class.st
> -TestAsserter >> assert: actualNumber closeTo: expectedNumber precision: margin [
I tried to remove the methods from Pharo (they were still there) and to re-introduce them but it does not work... What the hell...

2019-06-27 17:05 UTC, ErikOnBike commented on src/SUnit-Core/TestAsserter.class.st
> -TestAsserter >> assert: actualNumber closeTo: expectedNumber precision: margin [
If my bash history is correct as well as my brain ;-) I did the following:
git checkout f99498e -- src/SUnit-Core/ClassFactoryForTestCase.class.st
git checkout a57a347 -- src/SUnit-Core/TestAsserter.class.st
git add src/SUnit-Core/ClassFactoryForTestCase.class.st
git add src/SUnit-Core/TestAsserter.class.st
git commit -m "Revert 2 accidentally updated classes/files"

But check on the individual steps please.

2019-06-27 18:49 UTC, Ducasse commented
Julien can you also talk to damien because we were discussing that we need something that accumulate results (and not just a composite).

2019-06-27 18:50 UTC, Ducasse commented
44 tests broke so I relaunch the build to verify.

2019-06-27 19:16 UTC, jecisc commented
For the removed methods here is a fix: https://github.com/juliendelplanque/pharo/pull/1

2019-06-27 19:24 UTC, ErikOnBike commented
It might be me, but if I look at the file for TestAsserter in Github I see two methods with the same selector. This should not be possible, should it?!

File: https://github.com/pharo-project/pharo/blob/Pharo8.0/src/SUnit-Core/TestAsserter.class.st
Line (81): TestAsserter >> assert: actualNumber closeTo: expectedNumber precision: epsilon [
Line (90): TestAsserter >> assert: actualNumber closeTo: expectedNumber precision: margin [

Might this be the cause of having these in our PRs?

2019-06-27 19:27 UTC, jecisc commented
Indeed. In that case, it's acceptable that this PR remove one version of each.

Maybe two people added those methods and the merge of git kept both versions?

2019-06-27 20:25 UTC, juliendelplanque commented
@Ducasse yes I will discuss with him.

Here I did this small step because it slows us down at improving the test infrastructure...

2019-06-27 20:26 UTC, juliendelplanque commented
@ErikOnBike @jecisc Maybe this is a bug in Tonel. Tonel should do check that the file has no duplicated methods inside... I guess where there are, the behaviour is unspecified.

2019-06-28 07:05 UTC, juliendelplanque commented
I found a problem in the implementation, I will try to fix it and add unit test.

2019-06-28 09:06 UTC, juliendelplanque commented
Errors seems not related but I am not sure.

2019-06-28 14:25 UTC, jecisc approved these changes

2019-06-28 14:28 UTC, juliendelplanque commented
It should be ready now.

2019-06-28 14:45 UTC, juliendelplanque reviewed
Continue to fix stupid merge problems...

2019-06-28 14:45 UTC, juliendelplanque commented on src/SUnit-Core/TestAsserter.class.st
> +{ #category : #asserting }
```suggestion
{ #category : #asserting }
```

2019-06-28 14:45 UTC, juliendelplanque commented on src/SUnit-Core/TestAsserter.class.st
> +TestAsserter >> deny: actualNumber closeTo: expectedNumber [
```suggestion
TestAsserter >> deny: actualNumber closeTo: expectedNumber [
```

2019-06-28 14:45 UTC, juliendelplanque commented on src/SUnit-Core/TestAsserter.class.st
> +	"Tell whether the actualNumber and expectedNumber are NOT close to each others with a margin of
```suggestion
	"Tell whether the actualNumber and expectedNumber are NOT close to each others with a margin of
```

2019-06-28 14:45 UTC, juliendelplanque commented on src/SUnit-Core/TestAsserter.class.st
> +	 the default precision (see class-side method #defaultPrecisionsForCloseToComparison).
```suggestion
	 the default precision (see class-side method #defaultPrecisionsForCloseToComparison).
```

2019-06-28 14:45 UTC, juliendelplanque commented on src/SUnit-Core/TestAsserter.class.st
> +	"
```suggestion
	"
```

2019-06-28 14:45 UTC, juliendelplanque commented on src/SUnit-Core/TestAsserter.class.st
> +	self deny: actualNumber closeTo: expectedNumber precision: self class defaultPrecisionsForCloseToComparison
```suggestion
	self deny: actualNumber closeTo: expectedNumber precision: self class defaultPrecisionsForCloseToComparison
```

2019-06-28 14:45 UTC, juliendelplanque commented on src/SUnit-Core/TestAsserter.class.st
> +{ #category : #asserting }
```suggestion
{ #category : #asserting }
```

2019-06-28 14:45 UTC, juliendelplanque commented on src/SUnit-Core/TestAsserter.class.st
> +TestAsserter >> deny: actualNumber closeTo: expectedNumber precision: epsilon [
```suggestion
TestAsserter >> deny: actualNumber closeTo: expectedNumber precision: epsilon [
```

2019-06-28 14:45 UTC, juliendelplanque commented on src/SUnit-Core/TestAsserter.class.st
> +	"Tell whether the actualNumber and expectedNumber are NOT close to each others with a margin of epsilon."
```suggestion
	"Tell whether the actualNumber and expectedNumber are NOT close to each others with a margin of epsilon."
```

2019-06-28 14:45 UTC, juliendelplanque commented on src/SUnit-Core/TestAsserter.class.st
> +TestAsserter >> denyCollection: actualCollection includesAll: subcollection
```suggestion
TestAsserter >> denyCollection: actualCollection includesAll: subcollection [
```

2019-06-28 14:48 UTC, juliendelplanque commented on src/SUnit-Core/TestAsserter.class.st
>  		description: [ actualCollection asString , ' does not include all in ' , subcollection asString ]
```suggestion
		description: [ actualCollection asString , ' does not include all in ' , subcollection asString ]
]
```

2019-07-04 09:42 UTC, jecisc commented
There are 18 failures. I'm not sure it is related to this PR so I relaunched the CI.

2019-07-10 15:22 UTC, jecisc commented
CI crashed. I relaunched it.

2019-08-21 10:33 UTC, closed without merging