3484-Migrate-some-refactoring-UI-to-Spec-2-
guillep/pharo-core pull request #3728
Opened 2019-07-01 12:44 UTC by CafeKrem

migrate SycRefactoringPreview + SycMethodNameEditor to Spec 2

2019-07-01 12:45 UTC, CafeKrem commented
if you have some question tell me before Friday

2019-07-01 14:45 UTC, CafeKrem commented
sorry I forget to add the test package ...

2019-07-02 09:11 UTC, CafeKrem commented
I don't understand why the CI is broken, it said to me that UseOnlyForTest is undeclared but it's in my package of Test. could someone tell me why the CI is broken?

2019-07-02 12:00 UTC, jecisc requested changes

2019-07-02 12:00 UTC, jecisc commented on src/SystemCommands-RefactoringSupport-Test/UseOnlyForTest.class.st
> +{ #category : #'as yet unclassified' }
Methods should be categorized.

2019-07-02 12:00 UTC, jecisc commented on src/SystemCommands-RefactoringSupport-Test/MockSycRefactoringPreview.class.st
> +	mockTreeTableItem1 := MockTreeTableItem title: 'mockTreeTableItem1'.
No need for temporary variables. Just put the code in the array.

2019-07-02 12:00 UTC, jecisc commented on src/SystemCommands-RefactoringSupport-Test/SycMockPackageScope.class.st
> +{ #category : #'as yet unclassified' }
Category

2019-07-02 12:00 UTC, jecisc commented on src/SystemCommands-RefactoringSupport-Test/SycRefactoringPreview2Test.class.st
> +		items:
No need for temp vars

2019-07-02 12:00 UTC, jecisc commented on src/SystemCommands-RefactoringSupport-Test/SycRefactoringPreview2Test.class.st
> +	sycRefactoringPreview table
No need for temps.

2019-07-02 12:00 UTC, jecisc commented on src/SystemCommands-RefactoringSupport-Test/SycRefactoringPreview2Test.class.st
> +		assert: sycRefactoringPreview table items
You can use #assertCollection:hasSameElements: instead of casting to OrderedCollection.

2019-07-02 12:00 UTC, jecisc commented on src/SystemCommands-RefactoringSupport/SycMethodNameEditor.class.st
> +				selector: (UseOnlyForTest >> #bug:) selector
SystemCommands-RefactoringSupport should not depend on a class in the test package.

Maybe the example should be in the class comment and not in a method.

2019-07-02 12:00 UTC, jecisc commented on src/SystemCommands-RefactoringSupport-Test/MockSycRefactoringPreview2.class.st
> +		'title'
Is it normal to have an unused variable here?

2019-07-02 12:00 UTC, jecisc commented on src/SystemCommands-RefactoringSupport-Test/MockSycRefactoringPreview.class.st
> +		'title'
Shouéld we have an unused variable here?

2019-07-02 12:00 UTC, jecisc commented on src/SystemCommands-RefactoringSupport-Test/MockTreeTableItem.class.st
> +		'classsName',
Unused variables.

2019-07-02 12:00 UTC, jecisc commented on src/SystemCommands-RefactoringSupport-Test/SycMockClassScope.class.st
> +{ #category : #'as yet unclassified' }
Classification.

2019-07-02 12:00 UTC, jecisc commented on src/SystemCommands-RefactoringSupport-Test/SycMockRBRefactoring.class.st
> +		'class'
Unused variable.

2019-07-02 12:00 UTC, jecisc commented on src/SystemCommands-RefactoringSupport-Test/UseOnlyForTest.class.st
> +		'njghvijn',
Variables not used.

2019-07-02 12:00 UTC, jecisc commented on src/SystemCommands-RefactoringSupport-Test/package.st
> +Package { #name : #'SystemCommands-RefactoringSupport-Test' }
New packages need to be added into Pharo's baseline.

2019-07-02 14:03 UTC, jecisc requested changes

2019-07-02 14:03 UTC, jecisc commented on src/SystemCommands-RefactoringSupport-Test/SycMockClassScope.class.st
> +		'classs'
class is not used.

2019-07-04 09:39 UTC, jecisc requested changes

2019-07-04 09:39 UTC, jecisc commented on src/SystemCommands-RefactoringSupport-Test/MethodNameEditorTest.class.st
> +{ #category : #'action-input' }
```suggestion
{ #category : #running }
```

2019-07-04 09:39 UTC, jecisc commented on src/SystemCommands-RefactoringSupport-Test/MethodNameEditorTest.class.st
> +{ #category : #'action-accept' }
```suggestion
{ #category : #tests }
```

2019-07-04 09:39 UTC, jecisc commented on src/SystemCommands-RefactoringSupport-Test/MethodNameEditorTest.class.st
> +{ #category : #'action-cancel' }
```suggestion
{ #category : #tests }
```

2019-07-04 09:39 UTC, jecisc commented on src/SystemCommands-RefactoringSupport-Test/MethodNameEditorTest.class.st
> +{ #category : #'action-button-down' }
```suggestion
{ #category : #tests }
```

2019-07-04 09:39 UTC, jecisc commented on src/SystemCommands-RefactoringSupport-Test/MethodNameEditorTest.class.st
> +{ #category : #'action-button-down' }
```suggestion
{ #category : #tests }
```

2019-07-04 09:39 UTC, jecisc commented on src/SystemCommands-RefactoringSupport-Test/MethodNameEditorTest.class.st
> +{ #category : #'action-button-down' }
```suggestion
{ #category : #tests }
```

2019-07-04 09:39 UTC, jecisc commented on src/SystemCommands-RefactoringSupport-Test/MethodNameEditorTest.class.st
> +{ #category : #'action-button-up' }
```suggestion
{ #category : #tests }
```

2019-07-04 09:39 UTC, jecisc commented on src/SystemCommands-RefactoringSupport-Test/MethodNameEditorTest.class.st
> +{ #category : #'action-button-up' }
```suggestion
{ #category : #tests }
```

2019-07-04 09:39 UTC, jecisc commented on src/SystemCommands-RefactoringSupport-Test/MethodNameEditorTest.class.st
> +{ #category : #'action-button-up' }
```suggestion
{ #category : #tests }
```

2019-07-04 09:39 UTC, jecisc commented on src/SystemCommands-RefactoringSupport-Test/MethodNameEditorTest.class.st
> +{ #category : #'action-input' }
```suggestion
{ #category : #tests }
```

2019-07-04 09:39 UTC, jecisc commented on src/SystemCommands-RefactoringSupport-Test/MethodNameEditorTest.class.st
> +{ #category : #'action-input' }
```suggestion
{ #category : #tests }
```

2019-07-04 09:39 UTC, jecisc commented on src/SystemCommands-RefactoringSupport-Test/MethodNameEditorTest.class.st
> +{ #category : #'action-input' }
```suggestion
{ #category : #tests }
```

2019-07-04 09:39 UTC, jecisc commented on src/SystemCommands-RefactoringSupport-Test/MethodNameEditorTest.class.st
> +{ #category : #'action-input' }
```suggestion
{ #category : #tests }
```

2019-07-04 09:39 UTC, jecisc commented on src/SystemCommands-RefactoringSupport-Test/MethodNameEditorTest.class.st
> +{ #category : #'initialize-test' }
```suggestion
{ #category : #tests }
```

2019-07-04 09:39 UTC, jecisc commented on src/SystemCommands-RefactoringSupport-Test/MethodNameEditorTest.class.st
> +	""
```suggestion
```

2019-07-04 09:39 UTC, jecisc commented on src/SystemCommands-RefactoringSupport-Test/MethodNameEditorTest.class.st
> +{ #category : #'initialize-test' }
```suggestion
{ #category : #tests }
```

2019-07-04 09:39 UTC, jecisc commented on src/SystemCommands-RefactoringSupport-Test/MethodNameEditorTest.class.st
> +	""
```suggestion
```

2019-07-04 09:39 UTC, jecisc commented on src/SystemCommands-RefactoringSupport-Test/MethodNameEditorTest.class.st
> +{ #category : #'initialize-test' }
```suggestion
{ #category : #tests }
```

2019-07-04 09:39 UTC, jecisc commented on src/SystemCommands-RefactoringSupport-Test/SycRefactoringPreview2Test.class.st
> +{ #category : #'initialize-test' }
```suggestion
{ #category : #tests }
```

2019-07-06 19:14 UTC, Ducasse commented
Cyril is it ok for you?

2019-07-10 19:41 UTC, merged

2019-07-10 19:41 UTC, Ducasse commented
Cyril we will see if it breaks :)

2019-07-11 15:05 UTC, jecisc commented
@Ducasse I found a problem and I corrected it in https://github.com/pharo-project/pharo/pull/3892 with other cleanings.

2019-07-11 15:06 UTC, jecisc commented
The problem is related to a change in Spec that happened not so long ago.