Update-protocol-of-GTSpotterStep-isEmpty
guillep/pharo-core pull request #4143
Opened 2019-07-28 20:53 UTC by jecisc

Move GTSpotterStep>>isEmpty to *Deprecated80 to remove zz-deprecated protocol.

2019-07-28 21:02 UTC, guillep requested changes
Please, let's not put stuff in the deprecated package anymore...

2019-07-30 06:40 UTC, Ducasse commented
Guille you mean that we remove it?
Ok for me.

2019-07-30 09:40 UTC, guillep commented
> Guille you mean that we remove it?
I don't know, when was this method originally deprecated? Is this public API and there are any callers?

My understanding is that @jecisc wants to make sure that deprecations are effectively removed after a release cycle (like, when the pharo8 cycle starts, we can remove pharo7 deprecations).

My only point is that moving the deprecations to a single `DeprecatedXX` package does not solve that issue per se. We can do the same with a simple script (`methods select: #isDeprecated thenDo: #removeFromSystem`).

I understand however that having a package with deprecations from old versions can ease migration (thus the https://github.com/Ducasse/Migrator package, no?).

Still, **IF** we move deprecations to the Deprecated package (which I don't see the value due if we have migrator), the same commit/PR has to ensure that the deprecated class/method/trait is not used, otherwise, since the deprecated package is loaded at the end, it will break the build due to an unfulfillable dependency (happened in another PR with the class building messages).

Finally, being I'm less conservative I could also argue that deprecations could only apply yo public API methods. Internally used methods do not really require it... But sometimes (like this one) we cannot know because it is a super common message... :)

2019-07-30 09:54 UTC, Ducasse commented
I see.
What I would like 
- one package with public API deprecated method => Pushed in Migrator after
- fixing all users in Pharo (this is why I like that cyril changed the tests to not use category anymore -- I did the same internally to the class first and got distracted).
- remove broken not working old deprecated method. 
-

2019-08-05 09:40 UTC, jecisc commented
See discussion at: https://github.com/pharo-project/pharo/issues/4140#issuecomment-518162948

2019-08-06 21:20 UTC, merged