4194-Missing-refactoring-Abstract-instance-variable
guillep/pharo-core pull request #4199
Opened 2019-08-05 21:37 UTC by Ducasse

Fixes: #4194 this is my first Syc command. So feedback is welcomed. I checked and the refactoring is working well.

2019-08-12 08:13 UTC, MarcusDenker commented
testExternalIDEDependencies is failing with this PR

2019-08-12 09:08 UTC, jecisc commented
@MarcusDenker Closing and opening again the issue might fix the problem.

2019-08-12 13:41 UTC, Ducasse commented
I do not see why there would be a dependency problem because I did the same as create accessors.

2019-08-12 19:28 UTC, dionisiydk requested changes

2019-08-12 19:28 UTC, dionisiydk commented on src/SystemCommands-ClassCommands/SycAbstractAllInstVarAccessorsCommand.class.st
> +	^CmdContextMenuActivation byRootGroupItemOrder: 2.1 for: ClyClassContextOfFullBrowser
It needs to be defined in the full browser package Calypso-SystemTools-FullBrowser because system commands do not depend on calypso

2019-08-12 19:28 UTC, dionisiydk commented on src/SystemCommands-ClassCommands/SycAbstractAllInstVarAccessorsCommand.class.st
> +	^CmdContextMenuActivation byRootGroupItemOrder: 2.1 for: ClyClassContextOfFullBrowser
And I think it should go to new refactoring menu group

2019-08-12 19:28 UTC, dionisiydk commented on src/SystemCommands-ClassCommands/SycAbstractAllInstVarAccessorsCommand.class.st
> +	^CmdShortcutActivation  by: $a meta, $a meta for: ClyClass asCalypsoItemContext
Same here: commands do not depend on calypso. 
And I guess the shortcut is only for full browser - use ClyClassContextOfFullBrowser then

2019-08-13 09:43 UTC, Ducasse commented on src/SystemCommands-ClassCommands/SycAbstractAllInstVarAccessorsCommand.class.st
> +	^CmdContextMenuActivation byRootGroupItemOrder: 2.1 for: ClyClassContextOfFullBrowser
Yes but I have no idea how to do it. 
So I can integrate it and you fix it.

2019-08-13 09:44 UTC, merged