Add-deny-equivalent-of-assertCollection-hasSameElements
guillep/pharo-core pull request #4381
Opened 2019-08-21 15:11 UTC by jecisc

Add #denyCollection:hasSameElements to assertions

2019-08-21 15:14 UTC, gcotelli commented on src/SUnit-Core-Traits/TAssertable.trait.st
> +		description: (String streamContents: [ :stream | stream nextPutAll: 'Given collections match!' ])
Why `String streamContents:` and not directly: `'Given collections match!'` ?

2019-08-21 15:15 UTC, gcotelli commented on src/SUnit-Core/TestAsserter.class.st
> +		description: (String streamContents: [ :stream | stream nextPutAll: 'Given collections match!' ])
Why String streamContents: and not directly: 'Given collections match!' ?

2019-08-21 15:20 UTC, gcotelli requested changes
This need some test cases to verify proper behavior

2019-08-21 15:23 UTC, gcotelli commented on src/SUnit-Core-Traits/TAssertable.trait.st
> +		description: (String streamContents: [ :stream | stream nextPutAll: 'Given collections match!' ])
I think the implementation is not right or I'm misinterpreting the intention.
If you do: `self denyCollection: #(1 2) hasSameElements: #(1 2 4)` the test fails

2019-08-21 16:44 UTC, jecisc commented
@gcotelli Thanks! It's now fixed.

2019-08-21 17:05 UTC, gcotelli approved these changes
Looks good now

2019-08-22 10:09 UTC, MarcusDenker approved these changes

2019-08-22 11:25 UTC, merged