BaselineOf>>#packageRepositoryURL tries to find the repo url by looki…
guillep/pharo-core pull request #4722
Opened 2019-09-25 13:03 UTC by dupriezt

…ng at  iceberg repos  if it cannot find it otherwise

2019-09-25 13:03 UTC, dupriezt commented
Solves #4719

2019-09-25 13:15 UTC, jecisc approved these changes
I added this in Moose for multiple months and it works fine to manage a project with multiple baselines referencing themselves.

2019-09-25 18:42 UTC, Ducasse commented
Sounds good. Now I do not get how the current situation is working since we load the baseline after each commit. So why is it working there and not with your scenario. May be the loading is different.

2019-09-25 22:01 UTC, jecisc commented
It is working when you load with a Tonel or FileTree template but not a github:// or gitlab:// or bitbucket:// repository template.

2019-12-20 13:30 UTC, estebanlm requested changes
I don't understand why we want this, can you elaborate?

2019-12-20 13:30 UTC, estebanlm commented on src/Metacello-PharoExtensions/BaselineOf.extension.st
> +	url := self packageRepository
This can be solved a lot easier as: 

```Smalltalk
self packageRepository ifNotNil: [ :aRepository | ^ aRepository description ]
```

2019-12-20 13:30 UTC, estebanlm commented on src/Metacello-PharoExtensions/BaselineOf.extension.st
> +		packageName := self class package name.
I would extract this to a method.

2019-12-20 13:31 UTC, estebanlm commented
And in any case: Pharo9.0 :)

2019-12-20 14:28 UTC, jecisc commented
@estebanlm It's in case you have a project containing multiple baselines referencing themselves. 

For example in Moose you have BaselineOfMoose referencing BaselineOfFamix referencing BaselineOfFame. The three of them are in the same repository.

In that case, when declaring the dependency you need to give the repository template that invocked the loading of the baseline. For example, if you load BaselineOfMoose via `github://moosetechnology:v1.0.0/src`, then the repository for the Famix dependency need to be `github://moosetechnology:v1.0.0/src`. You cannot hardcode the version as you do when you declare external dependencies.

Here comes the method #packageRepositoryURL. This method gives you the right repository to give to internal dependencies. It is currently working if you already cloned the project and load the clone by referencing the folder (like the Pharo Jenkins is doing), but it does not work if you install a project directly from github/gitlab/bitbucket. 

This PR improve this by looking in the Iceberg registry to find the right repository URL in the project is registered there.

2020-02-19 16:33 UTC, jecisc commented
Ping

2020-03-15 12:56 UTC, guillep commented
This issue is stalled since december with requested changes.
I'll close it.

Please, feel free to re-open if the issues are going to be addressed.

2020-03-15 12:56 UTC, closed without merging

2020-03-15 13:04 UTC, jecisc commented
This is really useful to me and multiple people came to ask me how I did it to do it themself. So I think it is important to have it. 

The two request changes are nothing major, just details to make the code more readable. I think a ping would be enough instead of closing the PR with the risk of losing a change that is already working.

2020-03-15 13:20 UTC, guillep commented
> This is really useful to me and multiple people came to ask me how I did it to do it themself. So I think it is important to have it.

That's fair. Are you willing to push the issue then?
Because if I base myself on what is in this issue:
 - open in september
 - review in december
 - ping in february

It's more than six months, and pinging does not get the job done.
Let's at least agree on that.

> The two request changes are nothing major, just details to make the code more readable

I'll leave outside of the discussion that I think this solution is not a solution but a hack.
This is the kind of code that when we find it 1 year later we say "Why is this here?".
It introduces a brittle dependency against Iceberg that the dependency analyser could fail to find
(`self class environment at: #IceRepository`) and it depends on a non-public API of iceberg that may be subject to change.

Now, I could accept this, but we need to acknowledge this is not a good solution, even if this "works". Do we?

> I think a ping would be enough instead of closing the PR with the risk of losing a change that is already working.

History shows pinging is not enough. Thomas has his own agenda, and I understand that.
So somebody has to take responsibility for this, that's all.