fix-necontroller-can-be-nil
guillep/pharo-core pull request #4737
Opened 2019-09-26 11:54 UTC by estebanlm

controller can be nil (not always we want that). 
Also, controller could not come from morphic, so introduce this hidden dependency will not be beneficial.
demeters law!

2019-09-26 12:16 UTC, MarcusDenker approved these changes
ok

2019-09-26 12:38 UTC, MarcusDenker requested changes
Ups, test failing:

SubContextTest>>testReceiverArgument

2019-09-26 12:48 UTC, estebanlm commented
wow. 
how's that possible? :P

2019-09-28 06:36 UTC, MarcusDenker approved these changes

2019-09-28 06:36 UTC, merged