4866-ClyFullBrowser-classworldMenuOn-checks-if-nautilus-is-in-the-image
guillep/pharo-core pull request #4980
Opened 2019-10-24 18:19 UTC by myroslavarm

#4866 removed the ifTrue check for Nautilus as it's not in the system anymore

2019-10-24 18:31 UTC, jecisc reviewed
There is still a check for Nautilus just above. 
`self environment hasClassNamed: #Nautilus`

2019-10-24 19:11 UTC, myroslavarm commented
@jecisc removing that line makes calypso pop out of tools into the main "world" context menu which i'm guessing is far from ideal. i left the ifFalse checks because logically it makes sense that when it does not find nautilus (which it doesn't) that it does some other behaviour

2019-10-24 22:37 UTC, dionisiydk commented
@myroslavarm I also think all Nautilus part needs to be removed. If there is a side effect from it then it needs to be fixed

2019-10-25 08:35 UTC, jecisc requested changes

2019-10-25 08:35 UTC, jecisc commented on src/Calypso-SystemTools-FullBrowser/ClyFullBrowser.class.st
> +	^ self
Then now the method can be totally removed :)

2019-10-25 09:23 UTC, dionisiydk reviewed
Ah, exactly. It was just to override default browser menu

2019-10-27 08:02 UTC, merged