Executable comments
guillep/pharo-core pull request #4984
Opened 2019-10-25 01:59 UTC by mayonnaise-is-an-instrument

Added executable comments to a few Boolean methods.

2019-10-25 06:22 UTC, svenvc commented
the returns (^) in the blocks are not necessary

2019-10-25 07:51 UTC, jgfoster commented
This has a couple changes that overlap #4983 .

2019-10-25 09:26 UTC, jecisc requested changes
Thank you!

I did suggestions to remove the `^` as Sven said. 
In the github interface, in the "File" tab you can batch accept the suggestions and commit them.

2019-10-25 09:26 UTC, jecisc commented on src/Kernel/Boolean.class.st
> +	"false ifFalse: [^ 'This statement is false!'] >>> 'This statement is false!'"
```suggestion
	"false ifFalse: [ 'This statement is false!' ] >>> 'This statement is false!'" 
```

2019-10-25 09:26 UTC, jecisc commented on src/Kernel/Boolean.class.st
> +	"true ifFalse: [^ 'This statement is false!'] >>> nil"
```suggestion
	"true ifFalse: [ 'This statement is false!' ] >>> nil"
```

2019-10-25 09:26 UTC, jecisc commented on src/Kernel/Boolean.class.st
> +	"true ifFalse: [ ^'That is false!' ] ifTrue: [ ^'That is true!' ]  >>> 'That is true!'"
```suggestion
	"true ifFalse: [ 'That is false!' ] ifTrue: [ 'That is true!' ]  >>> 'That is true!'"
```

2019-10-25 09:26 UTC, jecisc commented on src/Kernel/Boolean.class.st
> +	"false ifFalse: [ ^'That is false!' ] ifTrue: [ ^'That is true!' ]  >>> 'That is false!'"
```suggestion
	"false ifFalse: [ 'That is false!' ] ifTrue: [ 'That is true!' ]  >>> 'That is false!'"
```

2019-10-25 09:26 UTC, jecisc commented on src/Kernel/Boolean.class.st
> +	"true ifTrue: [^ 'This statement is true!'] >>> 'This statement is true!'"
```suggestion
	"true ifTrue: [ 'This statement is true!' ] >>> 'This statement is true!'" 
```

2019-10-25 09:26 UTC, jecisc commented on src/Kernel/Boolean.class.st
> +	"false ifTrue: [^ 'This statement is true!'] >>> nil"
```suggestion
	"false ifTrue: [ 'This statement is true!' ] >>> nil"
```

2019-10-25 09:26 UTC, jecisc commented on src/Kernel/Boolean.class.st
> +	"true ifTrue: [ ^'That is true!' ] ifFalse: [ ^'That is false!' ]  >>> 'That is true!'"
```suggestion
	"true ifTrue: [ 'That is true!' ] ifFalse: [ 'That is false!' ]  >>> 'That is true!'"
```

2019-10-25 09:26 UTC, jecisc commented on src/Kernel/Boolean.class.st
> +	"false ifTrue: [ ^'That is true!' ] ifFalse: [ ^'That is false!' ]  >>> 'That is false!'"
```suggestion
	"false ifTrue: [ 'That is true!' ] ifFalse: [ 'That is false!' ]  >>> 'That is false!'"
```

2019-10-25 13:41 UTC, jgfoster commented
@jecisc, Thank you for making the suggestions. It is nice for newcomers to see the community collaboration and support!

2019-10-28 04:07 UTC, mayonnaise-is-an-instrument reviewed
commited the suggestions.

2019-10-28 05:04 UTC, jgfoster commented
Looks good to me.

2019-11-02 09:11 UTC, merged