type-for-the-entries-is-not-a-good-name
guillep/pharo-core pull request #5058
Opened 2019-11-05 23:17 UTC by myroslavarm

changed type to kind

2019-11-05 23:36 UTC, jecisc commented on src/NECompletion/CompletionModel.class.st
> +	kind := node receiver propertyAt: #type ifAbsent: [ ^ '' ].
You could also write it

`^ node receiver propertyAt: #type ifPresent: #name ifAbsent: ''`

2019-11-06 06:59 UTC, MarcusDenker requested changes
exactly here #type is a good name... the idea was that we use #type when we talk about types, but *not* for the method that returns the symbol for choosing the highlight color.

This is the method #type on the Entries hierarchy, which should be named maybe very explicitly #hightlightSymbol or something like that.

2019-11-06 08:36 UTC, myroslavarm commented
@MarcusDenker ok yeah sorry, fixed the method now - should be fine. And also i did update #title according to Cyril's suggestion, too.

2019-11-06 08:48 UTC, MarcusDenker approved these changes
Yes! Looks good.

2019-11-06 09:51 UTC, merged