5140-Browse-senders-crash-on-characters
guillep/pharo-core pull request #5141
Opened 2019-11-14 20:51 UTC by Ducasse

Fixes: #5140 at least $n sender and implementors do not break anymore. Now ClyTextEditor should have rewritten a bit rubSmalltalkEditor to avoid duplication.

2019-11-14 21:19 UTC, dionisiydk requested changes

2019-11-14 21:19 UTC, dionisiydk commented on src/Calypso-SystemTools-QueryBrowser/ClyTextEditor.extension.st
> +	selectedSelector isCharacter ifTrue: [ ^ self ].
Senders should normally work for any literals. We should just protect the check for class reference:
```Smalltalk
ClyBrowserMorph>>browseReferencesTo: aSymbol from: anEnvironment	
	...
	(aSymbol isSymbol and: [aSymbol first isUppercase]) ifTrue: [ 

```
#isSymbol will solve the issue

2019-11-17 14:08 UTC, dionisiydk approved these changes
thanks

2019-11-17 14:19 UTC, dionisiydk commented
For the future we should improve involved low level methods:
```Smalltalk
CompiledCode>>hasLiteralThorough: literal
        .....	
        2 to: self numLiterals - 1 "exclude header and methodClass or outerCode"
	   do:[:index | | lit |
		(((lit := self objectAt: index) literalEqual: literal)
		 or: [lit isArray and: [lit hasLiteral: literal]]) ifTrue:
			[^ true].
		(lit isMemberOf: CompiledBlock) ifTrue: [ (lit hasLiteralThorough: literal) ifTrue: [ ^true ] ] ].
	^ false 
```
It looks quite bad. It should simply delegate to literal instead of all these type checks.
In that case VariableBinding as a literal could implement such message and we will avoid class name analysis by users of senders query. Actually it is not a senders query but a literal references query. 

I would also simplify names of those methods. I do not get this "Thorough" word. Simple #refersToLiteral: is much better. In fact it is existing method with deprecation comment inside. I think we should rethink it

2019-11-18 07:24 UTC, Ducasse commented
100% with you. Can you open a separate issue because this code should be improved.

2019-11-18 07:25 UTC, Ducasse commented
https://github.com/pharo-project/pharo/issues/5154

2019-11-18 07:28 UTC, merged