[feedback needed] attempt to improve class comment for RemoteString
guillep/pharo-core pull request #5616
Opened 2020-01-31 19:19 UTC by hogoww

I don't think that's enough. I'd love some feedback on this

2020-02-05 12:15 UTC, MarcusDenker approved these changes

2020-02-21 15:24 UTC, myroslavarm commented on src/System-Sources/RemoteString.class.st
> +Allowed TextAttributes are TextFontChange, TextEmphasis, TextColor, TextDoIt, TextKern, TextLink, TextURL.
I would say "TextAttributes that are allowed are: ..."

2020-02-21 15:24 UTC, myroslavarm commented on src/System-Sources/RemoteString.class.st
> +The 'changes' file or 'file-in' file usually has a chunk that is just the source string of a method:
I'm not sure whether the changes and file-in files are meant to be different here. If they are, i would say "changes and file-in files usually have..."; if they aren't, i would say "the changes (or file-in) file usually has..."

2020-03-15 19:00 UTC, guillep requested changes
Hi @hogoww could you fix the couple of typos? Otherwise I think it is good :)

2020-03-15 19:00 UTC, guillep commented on src/System-Sources/RemoteString.class.st
> +I can return either a String or a Text. A chunck of code is followed by a second chunk (beginning with ]style[) containing style information. The encoding is like this:
Not all chunks have style. Only some of them.

2020-03-15 19:00 UTC, guillep commented on src/System-Sources/RemoteString.class.st
> +The 'changes' file or 'file-in' file usually has a chunk that is just the source string of a method:
They -> have ;)

2020-03-15 19:22 UTC, hogoww commented
Don't know why i cannot answer you on the conversation.
The typo is fixed.
The other one i'm not sure I understand the initial text. so i'm having trouble correcting it.
I'll see tomorrow with a rested mind.

2020-03-15 19:30 UTC, guillep commented on src/System-Sources/RemoteString.class.st
> +I can return either a String or a Text. A chunck of code is followed by a second chunk (beginning with ]style[) containing style information. The encoding is like this:
What this "wanted to mean" (:P) was that in a source file (sources, changes, fileouts) we store chunks of code. Some chunks are styled (they have parts in bold, or font color...). When a chunk is styled, it is followed by a second chunk (prefixed with something like ]sytle[), and specifying the style.

2020-03-15 19:38 UTC, hogoww commented
I actually used what you wrote because i think this was waaaaaaaaaay better, I hope you don't mind.
Thanks ! =)

2020-03-15 19:39 UTC, guillep commented
Not at all :P

I wrote that with a baby that was drooling on my arm and moving around, so if that was good enough...

> El 15 mar 2020, a las 20:38, hogoww <notifications@github.com> escribió:
> 
> 
> I actually used what you wrote because i think this was waaaaaaaaaay better, I hope you don't mind.
> Thanks ! =)
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub <https://github.com/pharo-project/pharo/pull/5616#issuecomment-599254670>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/AAFM5YQBWSAZVSBXIRFJV7DRHUVCRANCNFSM4KOMJCPA>.
>

2020-03-15 19:40 UTC, hogoww commented
Guess he inspired you :D

2020-03-17 22:13 UTC, guillep approved these changes
Good enough. I'll integrate

2020-03-17 22:13 UTC, merged

2020-03-17 22:13 UTC, guillep commented
Thanks :)