Compiler deprecate #methodMap
guillep/pharo-core pull request #5741
Opened 2020-02-23 07:27 UTC by MarcusDenker

Deprecate #debuggerMap: we can call these methods directly on the Context. Out "Map" is then natural meta object of a method: The AST after name analysis. It has all the information, we do not contruct any map. 

- deprecate #debuggerMap with a description what to do 
- remove the DebuggerMethodMapOpal class which just provided a backward compatible API.

2020-03-15 13:54 UTC, guillep requested changes
The deprecation comment is confusing...

Also it is not clear to me why this needs deprecation, and not just a direct removal :).
Is the debugger map a public concern? Or is it a private detail of the debugger?

I understand that we don't syntactically differentiate public from private methods, but that difference exist nevertheless.

2020-03-15 13:54 UTC, guillep commented on src/Debugging-Core/CompiledCode.extension.st
> +	^self deprecated: 'call the methods on Context and directly!'
For somebody falling into this method, it's not clear what are the methods to use instead.

2020-03-15 13:54 UTC, guillep commented on src/Debugging-Core/InstructionStream.extension.st
> +	^self deprecated: 'call the methods on Context and directly!'
Same same

2020-03-17 22:31 UTC, guillep commented
I'll time out this PR on friday :)

2020-03-18 14:46 UTC, MarcusDenker commented
So I once just blankly removed that method as you suggest, but that broke the CI testrunner (the travis one).

I would like to deprecate it for that at least for a little so people have it easier if if brakes. But I would not keep it for a whole release, just some week or so and then remove.

You are right that the information is not enough, I will update it with a list of methods to use.

2020-03-18 15:26 UTC, MarcusDenker commented
methods are:

tempNamed: name in: aContext -> aContext tempNamed: name

tempNamed: name in: aContext put: aValue ->  aContext tempNamed: name put: aValue

tempNamesForContext: aContext ->  aContext tempNames 

rangeForPC: aPC contextIsActiveContext: aBoolean  -> someContext pcRangeContextIsActive: aBoolean

I will update the PR with this

2020-03-18 15:28 UTC, guillep commented
> So I once just blankly removed that method as you suggest, but that broke the CI testrunner (the travis one).

Maybe there were senders? There should not be anymore, right?

> I would like to deprecate it for that at least for a little so people have it easier if if brakes. But I would not keep it for a whole release, just some week or so and then remove.

Ok, I'll open an issue as soon as this breaks.

> You are right that the information is not enough, I will update it with a list of methods to use.

As soon as you push that I'll merge.

2020-03-20 07:41 UTC, MarcusDenker commented
I will close this PR and do a new one where I will do the deprecation on the level of the DebuggerMethodMapOpal methods.

2020-03-20 07:41 UTC, closed without merging