5437 package names little queries
guillep/pharo-core pull request #5786
Opened 2020-02-28 04:01 UTC by daniapq

Add query methods with testing to solve #5437

2020-03-14 23:03 UTC, guillep requested changes
Please, check the comments I made in the code :)

2020-03-14 23:03 UTC, guillep commented on src/RPackage-Core/RPackageOrganizer.class.st
> +RPackageOrganizer >> endingWith: aString [
Why not `packagesEndingWith:`?
`endingWith:` suggests (following pharo naming conventions) that it will transform the package organizer, not return a collection of packages.

2020-03-14 23:03 UTC, guillep commented on src/RPackage-Core/RPackageOrganizer.class.st
> +RPackageOrganizer >> endingWith: aString [
Why not `packagesEndingWith:`? `endingWith:` suggests in pharo/smalltalk code conventions the method returns a new package organizer, not a collection of packages.

2020-03-14 23:03 UTC, guillep commented on src/RPackage-Core/RPackageOrganizer.class.st
> +RPackageOrganizer >> endingWithDigit [
Why not `packagesEndingWithDigit`?

2020-03-14 23:03 UTC, guillep commented on src/RPackage-Core/RPackageOrganizer.class.st
> +RPackageOrganizer >> includingWith: aString [
`includingWith:` is not good english.
Why not `packagesIncludingSubstring:`?

2020-03-14 23:03 UTC, guillep commented on src/RPackage-Core/RPackageOrganizer.class.st
> +RPackageOrganizer >> matching: aPatternString [
Why not `packagesMatching:`?

2020-03-14 23:03 UTC, guillep commented on src/RPackage-Core/RPackageOrganizer.class.st
> +RPackageOrganizer >> startingWith: aString [
Why not `packagesStartingWith:`?

2020-03-14 23:03 UTC, guillep commented on src/RPackage-Core/RPackageOrganizer.class.st
> +RPackageOrganizer >> startingWithDigit [
Why not `packagesStartingWithDigit`?

2020-03-14 23:04 UTC, guillep commented
Less important than the comments I made maybe, I'm a bit skeptical about the usefulness of these...
And some even raise a bell. For example, I'm not happy with `packagesIncludingSubstring:` because we don't check substrings in the package, we check substrings in the package name only. It's a bit misleading...

I wonder why having a single method `selectPackagesWithName: [ :name | ]` is not enough.

2020-03-15 06:56 UTC, Ducasse commented
Hi guille 
I agree with you and this is why I did not integrate it. 
I would favor selectPackages: [ :each | ] and may be one based on name.
I did not mention it before for obscure reasons. 
S.

2020-03-15 09:55 UTC, guillep commented
Ok I got it.

So, @daniapq , thanks for the contribution!
I'll close this PR, and clarify the original issue.
I think it's been good to have the conversation ^^.

2020-03-15 09:55 UTC, closed without merging