adding includingWith: , matching:  and startingWith: methodes. fixes #5437
guillep/pharo-core pull request #5808
Opened 2020-02-28 14:28 UTC by MoussaSak

2020-03-05 17:30 UTC, tesonep requested changes
@MoussaSak It is possible to add tests to it.
Thanks

2020-03-14 22:47 UTC, guillep commented
Hi @MoussaSak, what is the status of this PR?

2020-03-15 18:20 UTC, MoussaSak commented
Hello @tesonep and @guillep, okey i will add some tests on it.

2020-03-16 09:19 UTC, estebanlm requested changes

2020-03-16 09:19 UTC, estebanlm commented on src/RPackage-Core/RPackageOrganizer.class.st
> +{ #category : #accessing }
no this is bad. 
correct protocol is "testing" not "accessing"

2020-03-16 09:19 UTC, estebanlm commented on src/RPackage-Core/RPackageOrganizer.class.st
> +{ #category : #accessing }
same this one.

2020-03-16 09:19 UTC, estebanlm commented on src/RPackage-Core/RPackageOrganizer.class.st
> +RPackageOrganizer >> includingWith: aString [
"includingWith" has no meaning in English :)
`includesPackageWith:` ?

2020-03-16 09:19 UTC, estebanlm commented on src/RPackage-Core/RPackageOrganizer.class.st
> +RPackageOrganizer >> startingWith: aString [
in other thread @guillep suggested to use `packagesStartingWith:` instead.

2020-03-17 22:29 UTC, guillep commented
I'll close this, as this is duplicate from #5905

2020-03-17 22:29 UTC, closed without merging