4950-INVALID-ISSUE
guillep/pharo-core pull request #5811
Opened 2020-02-28 15:26 UTC by angelaclan

StirngLineEndingTest Class added.
It does test line endings in general, not only unixLineEndings, but unixLineEndings are included.

tests Line Endingless String to Be Equals
tests origin string to be reproduced From Target String And OriginLineEnding
tests TargetLine does not contain OriginLineEnding .
The test case is a subclass of parametrized tests, and it provides a matrix with the folowing cases 
 #targetLineEnding addOptions:
			{String cr.
			String lf.
			String crlf};
 #originLineEnding addOptions:
			{String cr.
			String lf.
			String crlf};
#templateString addOptions:
			{'I am a String{1}' . 
			'{1}I am a String' . 
			'I am a{1}String'.
			'{1}I am{1}a String{1}'};
The test case adds 108 new tests to the suit of string tests .

2020-02-28 15:51 UTC, MarcusDenker commented
changed the tittle to be nicer

2020-03-14 22:46 UTC, guillep commented
I restarted the CI

2020-03-15 13:36 UTC, guillep requested changes
It would be nice to fix these little details before integration.

I'll make sure myself that the issue introduces no dependencies as soon as we have a green build.

2020-03-15 13:36 UTC, guillep commented on src/Collections-Tests/StringLineEndingsTest.class.st
> +]
Is this comment a left over?

2020-03-15 13:36 UTC, guillep commented on src/Collections-Tests/StringLineEndingsTest.class.st
> +
Why so many empty lines?

2020-03-15 17:37 UTC, angelaclan commented
Le dim. 15 mars 2020 à 14:36, Guille Polito <notifications@github.com> a
écrit :

> *@guillep* requested changes on this pull request.
>
> It would be nice to fix these little details before integration.
>
> I'll make sure myself that the issue introduces no dependencies as soon as
> we have a green build.
> ------------------------------
>
> In src/Collections-Tests/StringLineEndingsTest.class.st
> <https://github.com/pharo-project/pharo/pull/5811#discussion_r392674426>:
>
> > +		copyReplaceAll: originLineEnding with: ''.
> +	targetWithoutLineEnding := testingSubjectWithTargetLineEnding
> +		copyReplaceAll: targetLineEnding with: ''.
> +	self assert: originWithoutLineEnding equals: targetWithoutLineEnding
> +]
> +
> +{ #category : #'as yet unclassified' }
> +StringLineEndingsTest >> testOriginStringCanBeProducedFromTargetStringAndOriginalLineEnding [
> +	
> +	| testingSubjectWithTargetLineEndingTransformedWithOriginalLineEnding |
> +	testingSubjectWithTargetLineEndingTransformedWithOriginalLineEnding := testingSubjectWithTargetLineEnding withLineEndings: originLineEnding .
> +	self assert: testingSubjectWithTargetLineEndingTransformedWithOriginalLineEnding equals: testingSubjectWithOriginLineEnding
> +	
> +	" transformedString := 'I'm a string <<lf>>' withLineEnding: <<cr>>
> +	>>> assert: I'm a string <<cr>> (transformedString) equals: I'm a string <<cr>> ( subjectWithOriginLineEnding )"
> +]
>
> Is this comment a left over?
>
  it was a comment to help clearify what this piece of code is doing since
the vars are long. if its more confusing then can remove it. or should move
to the top?

------------------------------
>
> In src/Collections-Tests/StringLineEndingsTest.class.st
> <https://github.com/pharo-project/pharo/pull/5811#discussion_r392674443>:
>
> > +	#category : #'Collections-Tests-Strings'
> +}
> +
> +{ #category : #'building suites' }
> +StringLineEndingsTest class >> testParameters [
> +	^ ParametrizedTestMatrix new
> +		forSelector: #targetLineEnding addOptions: {String cr . String lf . String crlf};
> +		forSelector: #originLineEnding addOptions: {String cr . String lf . String crlf};
> +		forSelector: #templateString addOptions: {'I am a String{1}'. '{1}I am a String' . 'I am a{1}String'. '{1}I am{1}a String{1}'};
> +		
> +		
> +		
> +		yourself
> +		
> +	
> +
>
> Why so many empty lines?
>

You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/pharo-project/pharo/pull/5811#pullrequestreview-374799701>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AH6BBTQQEDGY6RW7JYJKMULRHTKV7ANCNFSM4K5SNNVQ>
> .
>

2020-03-15 17:39 UTC, angelaclan commented
Le dim. 15 mars 2020 à 18:40, AN CL <angelaclan2015@gmail.com> a écrit :

>
>
> Le dim. 15 mars 2020 à 14:36, Guille Polito <notifications@github.com> a
> écrit :
>
>> *@guillep* requested changes on this pull request.
>>
>> It would be nice to fix these little details before integration.
>>
>> I'll make sure myself that the issue introduces no dependencies as soon
>> as we have a green build.
>> ------------------------------
>>
>> In src/Collections-Tests/StringLineEndingsTest.class.st
>> <https://github.com/pharo-project/pharo/pull/5811#discussion_r392674426>:
>>
>> > +		copyReplaceAll: originLineEnding with: ''.
>> +	targetWithoutLineEnding := testingSubjectWithTargetLineEnding
>> +		copyReplaceAll: targetLineEnding with: ''.
>> +	self assert: originWithoutLineEnding equals: targetWithoutLineEnding
>> +]
>> +
>> +{ #category : #'as yet unclassified' }
>> +StringLineEndingsTest >> testOriginStringCanBeProducedFromTargetStringAndOriginalLineEnding [
>> +	
>> +	| testingSubjectWithTargetLineEndingTransformedWithOriginalLineEnding |
>> +	testingSubjectWithTargetLineEndingTransformedWithOriginalLineEnding := testingSubjectWithTargetLineEnding withLineEndings: originLineEnding .
>> +	self assert: testingSubjectWithTargetLineEndingTransformedWithOriginalLineEnding equals: testingSubjectWithOriginLineEnding
>> +	
>> +	" transformedString := 'I'm a string <<lf>>' withLineEnding: <<cr>>
>> +	>>> assert: I'm a string <<cr>> (transformedString) equals: I'm a string <<cr>> ( subjectWithOriginLineEnding )"
>> +]
>>
>> Is this comment a left over?
>>
>   it was a comment to help clearify what this piece of code is doing
> since the vars are long. if its more confusing then can remove it. or
> should move to the top?
>
> ------------------------------
>>
>> In src/Collections-Tests/StringLineEndingsTest.class.st
>> <https://github.com/pharo-project/pharo/pull/5811#discussion_r392674443>:
>>
>> > +	#category : #'Collections-Tests-Strings'
>> +}
>> +
>> +{ #category : #'building suites' }
>> +StringLineEndingsTest class >> testParameters [
>> +	^ ParametrizedTestMatrix new
>> +		forSelector: #targetLineEnding addOptions: {String cr . String lf . String crlf};
>> +		forSelector: #originLineEnding addOptions: {String cr . String lf . String crlf};
>> +		forSelector: #templateString addOptions: {'I am a String{1}'. '{1}I am a String' . 'I am a{1}String'. '{1}I am{1}a String{1}'};
>> +		
>> +		
>> +		
>> +		yourself
>> +		
>> +	
>> +
>>
>> Why so many empty lines?
>>
>     i found the most update version is not saved!!! let me know what is
better to do for the comment i can change both issues and do pull request
again

>
> You are receiving this because you authored the thread.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/pharo-project/pharo/pull/5811#pullrequestreview-374799701>,
>> or unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/AH6BBTQQEDGY6RW7JYJKMULRHTKV7ANCNFSM4K5SNNVQ>
>> .
>>
>

2020-03-15 18:21 UTC, guillep commented
> " transformedString := 'I'm a string <<lf>>' withLineEnding: <<cr>> + >>> assert: I'm a string <<cr>> (transformedString) equals: I'm a string <<cr>> ( subjectWithOriginLineEnding )" +] Is this comment a left over?
> it was a comment to help clearify what this piece of code is doing since the vars are long. if its more confusing then can remove it. or should move to the top?

The problem is that it looks like normal code that was commented :).
It would be nice, instead, to have a written explanation in english around it to explain what it means. Because we don't get it by just reading it ;)

> better to do for the comment i can change both issues and do pull request again

As you please, you can also check with @sbragagnolo , he may help you in updating it.

Also, I realised that the code also has uncategorised methods ("as yet unclassified").
Test methods should be categorised as "test". Helpers as "helpers".

Thanks Angela :)

2020-03-15 21:16 UTC, angelaclan commented
Hi, the changes are done. let me know if its good. Thanks!

2020-03-16 10:55 UTC, guillep approved these changes
Thanks!

2020-03-16 10:55 UTC, merged