5872-workingDirectory-badly-resolved-if-its-path-contains-non-ascii-characters
guillep/pharo-core pull request #5873
Opened 2020-03-10 14:52 UTC by demarey

Fixes #5872 workingDirectory badly resolved if its path contains non-ascii characters

2020-03-11 11:15 UTC, tesonep commented
@demarey check that the modified method relies in a method that is loaded in a package that is loaded later. As this is core part of the system, we need to be aware that maybe #environment is not accessible.

2020-03-13 18:34 UTC, Ducasse commented
Christophe I let you have a look.

2020-03-14 22:19 UTC, guillep requested changes

2020-03-14 22:19 UTC, guillep commented on src/System-Platforms/OSPlatform.class.st
> +
Is the `asByteArray` needed?

2020-03-14 22:19 UTC, guillep commented on src/System-Platforms/OSPlatform.class.st
> +	^ self currentWorkingDirectoryRawPath decodeWith: self environment defaultEncoding
As @tesonep says, `environment` is an extension method, so this method is creating a circular dependency. (System-Platforms <-> System-OSEnvironments)

2020-03-18 17:16 UTC, guillep commented
@demarey could you give us an idea of when you'll be checking this?

2020-03-19 09:45 UTC, demarey commented
@guillep 
OSPlatform>>#currentWorkingDirectoryPath uses 
- #decodeWith: packaged in Zinc-Character-Encoding-Core (loaded in Bootstrap kernel group) => ok
- #defaultEncoding packaged in System-OSEnvironments. The problem here is that System-OSEnvironments package is loaded with UFFI because it uses a lot UFFI. BaselineOfUnifiedFFI is loaded either by MorphicCore or Athens (loaded by BaselineOfIDE).
I have the feeling that we should move the #defaultEncoding definition from OSEnvironment to OSPlatfrom. WDYT?

2020-03-19 09:52 UTC, guillep commented
> * #defaultEncoding packaged in System-OSEnvironments. The problem here is that System-OSEnvironments package is loaded with UFFI because it uses a lot UFFI. BaselineOfUnifiedFFI is loaded either by MorphicCore or Athens (loaded by BaselineOfIDE).
>   I have the feeling that we should move the #defaultEncoding definition from OSEnvironment to OSPlatfrom. WDYT?

Looks good enough to me. Can we try that?

2020-03-19 10:11 UTC, tesonep commented
Really cool analysis, it will be nice to extend the dependency analyser to
know where the packages are loaded and its dependencies.

What do you think?

On Thu, Mar 19, 2020, 10:46 demarey <notifications@github.com> wrote:

> @guillep <https://github.com/guillep>
> OSPlatform>>#currentWorkingDirectoryPath uses
>
>    - #decodeWith: packaged in Zinc-Character-Encoding-Core (loaded in
>    Bootstrap kernel group) => ok
>    - #defaultEncoding packaged in System-OSEnvironments. The problem here
>    is that System-OSEnvironments package is loaded with UFFI because it uses a
>    lot UFFI. BaselineOfUnifiedFFI is loaded either by MorphicCore or Athens
>    (loaded by BaselineOfIDE).
>    I have the feeling that we should move the #defaultEncoding definition
>    from OSEnvironment to OSPlatfrom. WDYT?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/pharo-project/pharo/pull/5873#issuecomment-601084793>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AACWY77EKNBNCSQ6DCTNXPLRIHSWLANCNFSM4LFAXZZQ>
> .
>

2020-03-19 10:12 UTC, tesonep commented
And also, I share it should be a good solution to move the method

On Thu, Mar 19, 2020, 11:11 tesonep@gmail.com <tesonep@gmail.com> wrote:

> Really cool analysis, it will be nice to extend the dependency analyser to
> know where the packages are loaded and its dependencies.
>
> What do you think?
>
> On Thu, Mar 19, 2020, 10:46 demarey <notifications@github.com> wrote:
>
>> @guillep <https://github.com/guillep>
>> OSPlatform>>#currentWorkingDirectoryPath uses
>>
>>    - #decodeWith: packaged in Zinc-Character-Encoding-Core (loaded in
>>    Bootstrap kernel group) => ok
>>    - #defaultEncoding packaged in System-OSEnvironments. The problem
>>    here is that System-OSEnvironments package is loaded with UFFI because it
>>    uses a lot UFFI. BaselineOfUnifiedFFI is loaded either by MorphicCore or
>>    Athens (loaded by BaselineOfIDE).
>>    I have the feeling that we should move the #defaultEncoding
>>    definition from OSEnvironment to OSPlatfrom. WDYT?
>>
>> —
>> You are receiving this because you were mentioned.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/pharo-project/pharo/pull/5873#issuecomment-601084793>,
>> or unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/AACWY77EKNBNCSQ6DCTNXPLRIHSWLANCNFSM4LFAXZZQ>
>> .
>>
>

2020-03-19 13:59 UTC, guillep commented
Thanks! Let's wait for the CI.

2020-03-20 09:56 UTC, guillep approved these changes
Good! tests are green!

2020-03-20 09:57 UTC, merged