5779 - Setting Display Scale Factor Changing
guillep/pharo-core pull request #5889
Opened 2020-03-13 20:01 UTC by David5i6

fixes #5779 

An if clause is used to return if it's not dragging the slider. MacOS and Windows, seems fixed.

Also a little comment in code and reformating for better readability.

-----

Please I made this change to correct a problem with Pharo 8 and Pharo 9 on Windows 10 and MacOS (not tested on Linux), but I don't have a complete vision of Morphic and Spec, Spec2.

The problem was that when movin the mouse over the slider it changes magically it's position, but not alwas. I saw that there was no "draggin" state, but instead the style of the slider is diferent and determines the state and used it to determine if slider is dragging.

I think adding a "dragging" and "dragging:" messages to set and retrieve the dragging state should be a cleaner way so I added that in a second commit.

2020-03-14 09:21 UTC, Ducasse commented
Thanks this is uper cool that you spend your time fixing such kind of glitches. We are to used to jump over them. Thanks a lot. This is important because there is no little changes not worth. 
This is because people give their energy to Pharo that it improves. So thank a lot.

2020-03-14 21:35 UTC, guillep requested changes
I'd like to know, at least to keep as documentation, a couple of points.
Maybe it could make sense to add some method/class comments?

Anyways, thanks :)

2020-03-14 21:35 UTC, guillep commented on src/Morphic-Widgets-Scrolling/Slider.class.st
> +		ifTrue: [slider borderColor: #inset. self dragging: true].
I don't understand why this depends on the border style. Could you add a comment on this?

2020-03-14 21:35 UTC, guillep commented on src/Morphic-Widgets-Scrolling/Slider.class.st
> +		ifTrue: [slider borderColor: #raised. self dragging: false].
Same same :)

2020-03-15 09:54 UTC, David5i6 commented
You're right. Due that the dragging state is now reflected on draggin variable there's no need to make the check against the borderColor.

I'm going to change it. Thanks !

2020-03-15 10:03 UTC, David5i6 commented
Re-reading the code, there some nonsense things. If mouse is down, It start dragging... but... ¿ It's possible to make the mouse down again without making it up ?

2020-03-15 10:19 UTC, guillep commented
Thanks, I like the changes :)

2020-03-15 10:19 UTC, merged

2020-03-15 10:22 UTC, David5i6 commented
sorry, I detected a little very rare cases after that. I'm gouing to send a merge request again with some code guards.

2020-03-15 10:26 UTC, guillep commented
Sure, thanks for the effort!!