2146-Hardcode-class-rewriter-and-searcher-in-RB-class
guillep/pharo-core pull request #6061
Opened 2020-03-31 11:49 UTC by LaurineDargaud

fix: #2146
From 62 to 23 references to RBParseTreeRewriter **with good name**: #parseTreeRewriterClass

2020-03-31 12:58 UTC, Ducasse commented
This is strange since it did not build.

2020-03-31 19:18 UTC, Ducasse commented
rekicking the build. There is something strange.

2020-04-01 09:18 UTC, guillep requested changes
Some infinite loops over here and there :)

2020-04-01 09:18 UTC, guillep commented on src/Refactoring-Core/RBAddParameterRefactoring.class.st
> +	rewriteRule := self parseTreeRewriter.
This looks like an infinite loop ;)

2020-04-01 09:18 UTC, guillep commented on src/Refactoring-Core/RBChangeMethodNameRefactoring.class.st
> +	rewriteRule := self parseTreeRewriter.
This one too

2020-04-01 09:18 UTC, guillep commented on src/Refactoring-Core/RBRenameMethodRefactoring.class.st
> +				ifTrue: [self parseTreeRewriter]
and this one :)

2020-04-02 11:59 UTC, LaurineDargaud commented on src/Refactoring-Core/RBAddParameterRefactoring.class.st
> +	rewriteRule := self parseTreeRewriter.
OK

2020-04-02 11:59 UTC, LaurineDargaud commented on src/Refactoring-Core/RBChangeMethodNameRefactoring.class.st
> +	rewriteRule := self parseTreeRewriter.
OK

2020-04-02 12:00 UTC, LaurineDargaud commented on src/Refactoring-Core/RBRenameMethodRefactoring.class.st
> +				ifTrue: [self parseTreeRewriter]
OK

2020-04-02 12:03 UTC, guillep approved these changes
Ok!

2020-04-02 13:47 UTC, guillep commented
Tests are fixed! There is a fleaky test only. I'll open an issue for that.

2020-04-02 13:48 UTC, merged