Fix #6448 Add a way to get a FileLocator when possible instead of a FileReference
guillep/pharo-core pull request #6449
Opened 2020-05-29 13:12 UTC by demarey

2020-05-29 13:13 UTC, demarey commented
When using paths with well-known origins, it would be nice to have the choice to get a file locator (late-bound reference) instead of a file reference. It can apply to known origins (e.g. home, documents, etc.)

2020-05-29 14:26 UTC, Ducasse commented
Christophe  

StringTest does not exists.
And it leads to a bug when reloading during the post bootstrap

[4] + /builds/workspace/uest_and_branch_Pipeline_PR-6449/64/bootstrap-cache/vmtarget/pharo --headless Pharo9.0-PR-compiler-64bit-eebe8ee.image --no-default-preferences loadHermes DeprecatedFileStream.hermes FileSystem-Core.hermes FileSystem-Disk.hermes --save --no-fail-on-undeclared
[64] pthread_setschedparam failed: Operation not permitted
[64] This VM uses a separate heartbeat thread to update its internal clock
[64] and handle events.  For best operation, this thread should run at a
[64] higher priority, however the VM was unable to change the priority.  The
[64] effect is that heavily loaded systems may experience some latency
[64] issues.  If this occurs, please create the appropriate configuration
[64] file in /etc/security/limits.d/ as shown below:
[64] 
[64] cat <<END | sudo tee /etc/security/limits.d/pharo.conf
[64] *      hard    rtprio  2
[64] *      soft    rtprio  2
[64] END
[64] 
[64] and report to the pharo mailing list whether this improves behaviour.
[64] 
[64] You will need to log out and log back in for the limits to take effect.
[64] For more information please see
[64] https://github.com/OpenSmalltalk/opensmalltalk-vm/releases/tag/r3732#linux
[64] SystemNotification: [Hermes] Reading DeprecatedFileStream.hermes
[64] SystemNotification: [Hermes] Installing DeprecatedFileStream.hermes
[64] SystemNotification: [Hermes] Remaining Undeclared variables in the system: #(#FileLocator #FileAttributeNotSupported #BISimpleFormatter #StartupPreferencesLoader #PragmaCollector #FileSystem)
[64] SystemNotification: [Hermes] Reading FileSystem-Core.hermes
[64] SystemNotification: [Hermes] Installing FileSystem-Core.hermes
[64] [31mError: Required class named: StringTest does not exists.

2020-05-29 14:59 UTC, demarey commented
StringTest does exist but, yes probably an error with the bootstrap process.
StringTest is probably loaded after FileSystem-Test.
I will look to fix that and also add a missing method to convert a file reference to a locator.

2020-05-29 23:20 UTC, jecisc requested changes
I proposed an optimized version of this feature. A little less than twice as fast. Should have the same behaviour.

2020-05-29 23:20 UTC, jecisc commented on src/FileSystem-Core/FileLocator.class.st
> +			^ locator resolve: (aPath relativeToPath: locator asPath) ].
```suggestion
	self supportedOrigins
		do: [ :origin | 
			| locator locatorPath |
			locator := self origin: origin.
			locatorPath := locator asPath.
			(locatorPath = aPath or: [ locatorPath containsPath: aPath ]) ifTrue: [ ^ locator resolve: (aPath relativeToPath: locatorPath) ] ].
```

2020-10-07 17:14 UTC, Ducasse commented
I do not know when is the last time this issue was validated but we will see.

2020-10-10 16:21 UTC, merged