6504-slotNames-is-defined-in-ClassDescription-but-invoked-from-Behavior
guillep/pharo-core pull request #6603
Opened 2020-06-15 11:50 UTC by MarcusDenker

- move #definesSlotNamed: to ClassDescription like al the other slot methods
- take this chance to redo the PR to move all extension methods of Slot class to the extended classes

fixes #6504

2020-06-17 10:14 UTC, guillep requested changes
I think all changes related to `ClassDescription`, `Behavior`, closures are ok.

However, all the String related stuff is strange and pollutes the String API, for something not really useful.

2020-06-17 10:14 UTC, guillep commented on src/Collections-Strings/String.class.st
> +]
Why is this in String?

2020-06-17 10:14 UTC, guillep commented on src/Collections-Strings/String.class.st
> +
Shouldn't this be an extension method?

2020-06-17 10:14 UTC, guillep commented on src/Collections-Strings/String.class.st
> +]
Should this be an extension method?

2020-06-17 10:14 UTC, guillep commented on src/Collections-Strings/String.class.st
> +]
Same, Should this be an extension method?

2020-06-17 10:14 UTC, guillep commented on src/Collections-Strings/String.class.st
> +]
Why is this in String? The only user is Slot. This should be moved to the Slot class...

```smalltalk
aSymbol isPseudovariableName ifTrue: [ 
		^ InvalidSlotName signalFor: aSymbol ].
```

```smalltalk
(self isPseudovariableName: aSymbol) ifTrue: [ 
		^ InvalidSlotName signalFor: aSymbol ].

```

I don't see the value of this being in `String`

2020-06-17 10:14 UTC, guillep commented on src/Collections-Strings/Symbol.class.st
> +]
Why is this in `Symbol`? this should be at least in an extension method.

This is not good packaging...

2020-06-17 10:14 UTC, guillep commented on src/Collections-Strings/Symbol.class.st
> +]
Same same

2020-06-17 10:14 UTC, guillep commented on src/Collections-Strings/Symbol.class.st
> +
Same.

2020-06-17 10:14 UTC, guillep commented on src/Collections-Unordered/Dictionary.class.st
> +
Again. I don't see why this should be in Dictionary. This is no general use of dictionary.
Either we need a special "variable" dictionary. Or all this logic should be in the client.

2020-06-17 10:14 UTC, guillep commented on src/System-Support/SystemDictionary.class.st
> +
This looks pretty similar to `Dictionary >> declareVariable: newGlobal from: aDictionary` no?

2020-06-17 10:49 UTC, MarcusDenker commented
Thanks! The only problem now I that I can not load the PR...  changes are done in an order that is bad (it remove a method that it then needs?)

I will redo it step by step with multiple PRs taking the review into account (I let it open for that)

2020-06-17 11:10 UTC, Ducasse commented
Thank marcus. I agree with the comments of Guille. I try to avoid to have these as* on Symbol and String because it means that we cannot dispatch.

2020-06-22 06:47 UTC, MarcusDenker commented
I added everything to my backlog to be done step by step, I close this as it will soon be conflicting with other merged PR.

2020-06-22 06:47 UTC, closed without merging