21034 ep monitor classreset should not create a new instance if current is already empty
guillep/pharo-core pull request #698
Opened 2018-01-23 00:38 UTC by VincentBlondeau

https://pharo.fogbugz.com/f/cases/21034/EPMonitor-class-reset-should-not-create-a-new-instance-if-current-is-already-empty

2018-01-23 19:42 UTC, jecisc approved these changes

2018-01-24 16:02 UTC, tinchodias requested changes

2018-01-24 17:13 UTC, VincentBlondeau commented on src/Epicea/EpRenameClassRefactoring.class.st
> -	^ RBRenameClassRefactoring new
No it was not. I thought it was an automatic refactoring that was let uncommitted

2018-01-24 18:27 UTC, tinchodias commented on src/Epicea/EpRenameClassRefactoring.class.st
> -	^ RBRenameClassRefactoring new
So what do we proceed? could you remove this change and commit to this branch?

2018-01-24 18:43 UTC, VincentBlondeau commented
@tinchodias: Ok for me

2018-01-24 19:31 UTC, tinchodias approved these changes
ok for me

2018-01-25 11:31 UTC, merged

2018-01-25 11:31 UTC, estebanlm commented
but I hate your formatting ;)