[fix] fix #6937 with tests
guillep/pharo-core pull request #7028
Opened 2020-07-31 13:55 UTC by hogoww

Thanks @Alisu for the work :)

2020-07-31 14:11 UTC, StephanEggermont commented
Please rename. Describe the issue

2020-07-31 18:02 UTC, MarcusDenker commented
Tried the CI artefact image: bug is fixed

2020-08-01 07:10 UTC, hogoww commented
@MarcusDenker We had an infinite loop while trying out the Spec tests locally on Unix. 
Could we relaunch the CI, just in case?

2020-08-10 18:38 UTC, dionisiydk requested changes
I think it can be simpler. See code suggestion

2020-08-10 18:38 UTC, dionisiydk commented on src/Spec2-Adapters-Morphic/SpNotebookTabSelectorMorph.class.st
>  		selectedIndex = anInteger
```suggestion
		selectedIndex = anInteger & (selectedIndex <= self tabs size)
```

2020-08-10 18:38 UTC, dionisiydk commented on src/Spec2-Adapters-Morphic/SpNotebookTabSelectorMorph.class.st
> +				self tabs ifNotEmpty: [self selectedIndex: self selectedIndex - 1 \\ self tabs size + 1 ] ]
```suggestion
				self tabs ifNotEmpty: [ self selectedIndex: selectedIndex ]]
```

2020-08-10 19:55 UTC, hogoww commented
I haven't tried them out, but I trust you @dionisiydk =)

2020-08-11 07:39 UTC, hogoww commented
errored test: #testErrorCaughtAndDefferedIfExceptionSignaledAtStartupWhenStartupUiManagerActive.
Does not look related to me.

2020-08-11 08:48 UTC, dionisiydk approved these changes
thanks

2020-08-16 10:00 UTC, merged