Adding the tools to stylize the text with IconStyler in real time
guillep/pharo-core pull request #7051
Opened 2020-08-06 09:27 UTC by lesueur-philippe

Adding in calypso the underlining and overlining of error nodes.
There are two parts 
- the copy of IconStyler to "reset its sub-classes", with new sub-classes
- the modification of ClyMethodEditor to allow the styling in method tabs

2020-08-18 15:12 UTC, Ducasse commented
One solution to remove the duplication between iconStyler and iconStylerRT is probably to make sure that icon styler can get a list of the subclasses it will query instead of doing 

```
styleText: textModel withAst: ast [
 	self allSubclassesDo: [ :styleClass | 
 			styleClass shouldStyle
 				ifTrue: [ ast acceptVisitor: (styleClass style: textModel) ] ]
```

2020-08-18 16:43 UTC, dionisiydk commented
Hi @lesueur-philippe . 
Could you explain why do you consider the old styler as not real time? When I edit code the highlighting is definitely changed dynamically as I typed. What the difference?

2020-08-18 16:57 UTC, lesueur-philippe commented
Hi,
The real time styling of the text is made by SHRBTextStyler and only
changes the color and the typo of the texte. IconStylerRealTime uses the
same model as IconStyler to overline or underline the text and create icons
with messages on the left bar.
But IconStyler was doing it on compilation where IconStylerRealTime does it
when the text is changed.

So, it is a complementary styler to further the feedback on errors.

Le mar. 18 août 2020 à 18:43, Denis Kudriashov <notifications@github.com> a
écrit :

> Hi @lesueur-philippe <https://github.com/lesueur-philippe> .
> Could you explain why do you consider the old styler as not real time?
> When I edit code the highlighting is definitely changed dynamically as I
> typed. What the difference?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/pharo-project/pharo/pull/7051#issuecomment-675589661>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/APB4DQYBBP4LKSL72C3E6ILSBKVUNANCNFSM4PWMOC2Q>
> .
>

2020-08-18 17:44 UTC, dionisiydk commented on src/Reflectivity-Tools/IconStylerRealTime.class.st
> +IconStylerRealTime class >> styleText: textModel withAst: ast [
I believe we can avoid separate styler hierarchy. We can have a method on IconStyler like:
```Smalltalk
IconStyler>>styleTextForRealTimeHighlighting: textModel withAst: ast
	self allSubclassesDo: [ :styleClass | 
			styleClass shouldStyleTextInRealTime ifTrue: [...]]
```
Then we just need to decide which classes should return true from #shouldStyleTextInRealTime.

2020-08-18 17:44 UTC, dionisiydk requested changes
And you did not comment new classes.

2020-08-18 17:48 UTC, dionisiydk commented on src/Reflectivity-Tools/SemanticVariableIconStyler.class.st
> +SemanticVariableIconStyler >> addIconStyle: aNode from: start to: stop color: aColor [
It seems this method is duplicated in all classes. Maybe I do not see the difference. But it is also a sign to refactor common parts.

2020-08-19 09:31 UTC, Ducasse commented
Yes I agree denis. For now we will integrate it and I already created an issue https://github.com/pharo-project/pharo/issues/7126

2020-08-19 09:33 UTC, merged