Integrate changes of Epicea BleedingEdge
guillep/pharo-core pull request #751
Opened 2018-01-26 23:16 UTC by VincentBlondeau

Resolve https://pharo.fogbugz.com/f/cases/21161/Epicea-do-not-create-directory-on-startUp-if-EpMonitor-is-not-logging#BugEvent.196160

2018-01-26 23:18 UTC, jecisc requested changes

2018-01-26 23:18 UTC, jecisc commented on src/OmbuTests/OmSessionStoreNameStrategyTest.class.st
> -	super setUp.
I think this change is unintended.

2018-01-26 23:27 UTC, VincentBlondeau commented on src/OmbuTests/OmSessionStoreNameStrategyTest.class.st
> -	super setUp.
indeed! Updated ;)

2018-01-26 23:31 UTC, jecisc approved these changes

2018-01-31 15:45 UTC, jecisc commented on src/OmbuTests/OmSessionStoreNameStrategyTest.class.st
> +	super tearDown
For a fix this small I think it should be ok :)

2018-01-31 16:04 UTC, astares commented on src/OmbuTests/OmSessionStoreNameStrategyTest.class.st
> +	super tearDown
Be aware of https://github.com/pharo-project/pharo/pull/778 and https://pharo.fogbugz.com/f/cases/21103/Super-tearDown-need-to-be-called-as-last-message-in-tearDown-of-Ombu-tests

2018-01-31 17:20 UTC, VincentBlondeau commented
I updated the test tearDown

2018-01-31 17:51 UTC, tinchodias approved these changes

2018-02-01 10:38 UTC, MarcusDenker commented
now we have a conflict:

Conflicting files
src/OmbuTests/OmSessionStoreNameStrategyTest.class.st

2018-02-01 13:50 UTC, astares commented
Yes - because as you can see on the diff OmSessionStoreNameStrategyTest >> tearDown  is still included (because still changed)

2018-02-01 14:28 UTC, MarcusDenker commented
What is strange is that another issue now is constantly failing due to a test failing in
OmSessionStoreTest

2018-02-01 21:54 UTC, MarcusDenker commented
can it be that the tearDown change is problematic? Since we merged that, we have always OmDeferrerTest and OmSessionStoreTest failing

2018-02-01 22:04 UTC, astares commented
Yes it was already merged and is also not related to this bug. It should be reverted to the original one so you have no diff at all on that method. Otherwise you will have a conflict.

2018-02-02 08:41 UTC, merged

2018-02-02 22:16 UTC, tinchodias commented
I wonder what's the reason to force #tearDown as last message

2018-02-02 22:18 UTC, jecisc commented
@tinchodias Check the discussion here: 

https://github.com/pharo-project/pharo/pull/767