Fixed #7400. Added a visitSelectorNode to RBProgramNodeVisitor and fixed RBMessageNode >> selector
guillep/pharo-core pull request #7647
Opened 2020-10-31 17:04 UTC by olekscode

## Problem

`RBSelectorNode` implemented the following method:
```Smalltalk
RBSelectorNode >> acceptVisitor: aProgramNodeVisitor
	^ aProgramNodeVisitor visitSelectorNode: self
```
However, the `visitSelectorNode:` was not implemented by `RBProgramNodeVisitor`.

## What we did

So we added a simple implementation (inspired by `RBProgramNodeVisitor>>visitVariableNode:`) which returns the node itself.
We also modified `RBProgramNodeVisitor >> visitMessageNode:` to make sure that it calls `visitSelectorNode:`.

Additionally, we have improved the implementation of `RBMessageNode >> selector` from this:

```Smalltalk
RBMessageNode >> selector
	^ [ selector value ] on: Error do: [selector].
```
To this:
```Smalltalk
RBMessageNode >> selector
	^ selector value
```
Because the selector variable should *always* contain an `RBSelectorNode` and not a `ByteString`.

2020-11-02 08:12 UTC, MarcusDenker commented
failing tests in RubSmalltalkEditorTest

2020-11-02 08:45 UTC, guillep commented
I'll take a look this morning!

2020-11-05 09:41 UTC, guillep requested changes
I think the changes are good!

However, the tests need to be fixed. @olekscode could you take a look so we can integrate this?

2020-11-27 10:38 UTC, hogoww commented
fixes #7647 (reference was missing, so I missed this PR at first)

2020-12-22 15:09 UTC, closed without merging