8546-Environment-variables-access-sometimes-failing-with-ERROR-INVALID-HANDLE
guillep/pharo-core pull request #8547
Opened 2021-02-10 12:57 UTC by tesonep

Adding a work around to for getting the environment variables in Windows.

Fixes #8546
Fixes https://github.com/pharo-project/opensmalltalk-vm/issues/164

2021-02-10 13:40 UTC, gcotelli requested changes

2021-02-10 13:40 UTC, gcotelli commented on src/System-OSEnvironments/Win32Environment.class.st
> +		lastErrCode = "ERROR_ENVVAR_NOT_FOUND" 16r000000CB ifTrue: [ ^ aBlock value ].
Why not put this magic constant in a Pool or at least in a method?

2021-02-14 09:49 UTC, Ducasse commented
Gabriel can you open a new bug entry for your suggestion?

2021-02-14 09:49 UTC, merged

2021-02-19 11:26 UTC, gcotelli commented
> Gabriel can you open a new bug entry for your suggestion?

Done. #8588