#8992 Unwind mechanism during termination is broken, skips multiple unwind blocks and corrupts the image
guillep/pharo-core pull request #8993
Opened 2021-04-08 11:57 UTC by isCzech

Fixes #8992

2021-04-10 09:03 UTC, isCzech commented
As explained in #8992 the test failures are a result of fixing the termination bugs (unwind errors during termination).

2021-04-10 11:26 UTC, dionisiydk requested changes
I will look into the logic later.
But your should really add tests to describe found issues.

2021-04-10 11:32 UTC, dionisiydk requested changes
only brief look: there are methods on contexts for "unwind variables"

2021-04-10 11:32 UTC, dionisiydk commented on src/Kernel/Process.class.st
> +		[(ctxt tempAt:2) ifNotNil: [outerMost := ctxt]].
```suggestion
		[ctxt unwindComplete ifNotNil: [outerMost := ctxt]].
```

2021-04-10 11:32 UTC, dionisiydk commented on src/Kernel/Process.class.st
> +			ctx closure == (outerMost tempAt: 1)]) ifNotNil: [:inner |
```suggestion
			ctx closure == outerMost unwindBlock]) ifNotNil: [:inner | 
```

2021-04-10 11:32 UTC, dionisiydk commented on src/Kernel/Process.class.st
> +			ctx closure == (outerMost tempAt: 1)]) ifNotNil: [:inner |
```suggestion
			ctx closure == outerMost unwindBlock]) ifNotNil: [:inner | 
```

2021-04-10 11:32 UTC, dionisiydk commented on src/Kernel/Process.class.st
> +			unwindBlock := ctxt tempAt: 1.
```suggestion
			unwindBlock := ctxt unwindBlock.
```

2021-04-10 11:32 UTC, dionisiydk commented on src/Kernel/Process.class.st
> +			ctxt tempAt: 2 put: true.
```suggestion
			ctxt unwindComplete: true.
```

2021-04-10 11:32 UTC, dionisiydk commented on src/Kernel/Process.class.st
> +		(ctxt tempAt: 2) ifNil: [
```suggestion
		ctxt unwindComplete ifNil: [
```

2021-04-17 20:41 UTC, isCzech commented
Hi @dionisiydk ,
sorry for not responding earlier, I was not aware of your commenting this. Thanks for suggesting replacing tempAt with accessors - way more readable!

2021-06-14 12:10 UTC, Ducasse commented
We are somehow reorganising the engineering team as well as our research team (this happen every 12 years),  under pressure with contracts and release, and flooded by interns (we did an effort because of COVID students do not find internships). I checked the tests and this is super nice that we get all these tests. @estebanlm this is issue may be related to the issue of the unwind on GTK.

2021-06-18 07:40 UTC, estebanlm commented
hi, all of this is very important and we definitively want this code... but the nature of this change is so risky that I will defer the inclusion of this code to first iterations of P10 (so we have time to debug if something happens).

2021-06-18 08:50 UTC, isCzech commented
Hi @estebanlm , @Ducasse ,

Thank you for your interest! This code is a part of a more complete package overhauling the unwind process during termination. Cuis already integrated the complete code; you can check it out (update the image to latest changes) - including many more tests and examples. Squeak has integrated a portion of it so far. The difference between Pharo and Cuis/Squeak is Pharo refactored #terminate into smaller methods a while ago (and unfortunately including the bugs) but I believe the whole overhauled code is still applicable with reasonable effort.

There's a danger though a future code may try to "learn to live" with the current termination bugs and deficiencies, balance them out on "higher levels" (e.g. debugger) or even "use" them: I've already found two tests that kind of do that and propose to mark them 'expected failure'. They use the "unwind error" to achieve certain outcome but this "unwind error" shouldn't be there at all in the first place :) From this angle I'd say the sooner the better.

The relevant discussions are here:
http://forum.world.st/Solving-multiple-termination-bugs-summary-amp-proposal-td5128285.html#a5130200
https://lists.cuis.st/mailman/archives/cuis-dev/2021-June/003187.html
https://lists.cuis.st/mailman/archives/cuis-dev/2021-May/003171.html

Thanks again, please let me know how I can help.

2021-06-19 06:16 UTC, Ducasse commented
Thanks for the info. Our problem is that we do not change the ground in post beta pre release phase. 
The system is like that since at least 10 years. And we have customers.

2021-06-19 07:15 UTC, isCzech commented
> @Ducasse wrote:
> As a general principle we do not copy code from other systems because we do not want that people think that we are stealing their code. We do not look at their solution for political reasons.

This is my solution and I'm offering it to you. As well as I offered it to Cuis and Squeak. And as a sole author I'm offering to adapt the solution to your particular situation in Pharo 10 - did you mean this is against your policy? I hope not :)

2021-06-19 09:13 UTC, Ducasse commented
No this is not against our policy. This is why this is important that you do it. 
Now I just wanted to tell that we (the core Pharo team) do not look at other code because we do not want that people think that we are stealing any clever ideas. In the past some silly people told us that Pharo destroyed Smalltalk, while many others think the inverse :).

2021-06-19 09:25 UTC, isCzech commented
>  No this is not against our policy. This is why this is important that you do it.

Thanks, I'm relieved :)

> Now I just wanted to tell that we (the core Pharo team) do not look at other code because we do not want that people think that we are stealing any clever ideas. In the past some silly people told us that Pharo destroyed Smalltalk, while many others think the inverse :).

I can only say without your sharing so many resources I'd probably not be doing any Smalltalk at all :D Thanks again!

2021-06-19 11:12 UTC, Ducasse commented
:)
Thanks. May be we will have to revisit the concurrent programming book. But I would like to release Pharo by Example 90. 

Pharo 90 was super difficult with Covid impact and we enhanced so many things that it went far too lengthly. We are brainstorming on how to change our process to get faster. But large changes are just large. We hope to open the Pharo 10 alpha branch by the end of July. And we want to learn how to handle subtle PR more efficiently. 
So I hope Pharo 10 will be in another age :)

2021-11-24 09:26 UTC, guillep commented
Hi all, it's been really difficult to review the batch of issues (#8567 , #8845, #9137, #8993, #8509).
We have spent in the last internal sprints several hours taking a look at them, but it is a reality that those changes are difficult to review, some like #8567 are very big, their effects in the system are difficult to foresee independently and even worse in combination.

@tesonep is correctly (!!) proposing to my ear that we make a single PR joining all of them to reduce the merge noise, let the CI test the combination of all issues. I then propose that we eagerly merge this (meta) PR and be ready to quickly apply hot-fixes as soon as possible or revert it in case of fire.

Thoughts? @dionisiydk @Ducasse @isCzech @estebanlm

2021-11-24 10:13 UTC, guillep commented
Superseeded by https://github.com/pharo-project/pharo/pull/10429

2021-11-24 10:13 UTC, closed without merging